{"kind":"symbol","identifier":{"url":"doc:\/\/com.kaleyra.KaleyraVideoSDK\/documentation\/KaleyraVideoSDK\/ChatViewController\/position(for:)","interfaceLanguage":"swift"},"schemaVersion":{"minor":3,"patch":0,"major":0},"sections":[],"hierarchy":{"paths":[["doc:\/\/com.kaleyra.KaleyraVideoSDK\/documentation\/KaleyraVideoSDK","doc:\/\/com.kaleyra.KaleyraVideoSDK\/documentation\/KaleyraVideoSDK\/ChatViewController","doc:\/\/com.kaleyra.KaleyraVideoSDK\/documentation\/KaleyraVideoSDK\/ChatViewController\/UIBarPositioningDelegate-Implementations"]]},"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/kaleyravideosdk\/chatviewcontroller\/position(for:)"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/kaleyravideosdk\/chatviewcontroller\/position(for:)"]}],"primaryContentSections":[{"kind":"declarations","declarations":[{"languages":["swift"],"tokens":[{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"position"},{"kind":"text","text":"("},{"text":"for","kind":"externalParam"},{"kind":"text","text":" "},{"text":"bar","kind":"internalParam"},{"kind":"text","text":": "},{"preciseIdentifier":"c:objc(pl)UIBarPositioning","text":"UIBarPositioning","kind":"typeIdentifier"},{"kind":"text","text":") -> "},{"kind":"typeIdentifier","text":"UIBarPosition","preciseIdentifier":"c:@E@UIBarPosition"}],"platforms":["iOS"]}]}],"abstract":[{"type":"text","text":"Inherited from "},{"type":"codeVoice","code":"UIBarPositioningDelegate.position(for:)"},{"type":"text","text":"."}],"metadata":{"symbolKind":"method","roleHeading":"Instance Method","navigatorTitle":[{"kind":"identifier","text":"positionForBar:"}],"role":"symbol","platforms":[{"introducedAt":"15.0","deprecated":false,"unavailable":false,"beta":false,"name":"iOS"}],"fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"position","kind":"identifier"},{"text":"(","kind":"text"},{"text":"for","kind":"externalParam"},{"kind":"text","text":": "},{"preciseIdentifier":"c:objc(pl)UIBarPositioning","text":"UIBarPositioning","kind":"typeIdentifier"},{"text":") -> ","kind":"text"},{"preciseIdentifier":"c:@E@UIBarPosition","kind":"typeIdentifier","text":"UIBarPosition"}],"modules":[{"name":"KaleyraVideoSDK"}],"title":"position(for:)","externalID":"c:@CM@KaleyraVideoSDK@objc(cs)ChatViewController(im)positionForBar:"},"references":{"doc://com.kaleyra.KaleyraVideoSDK/documentation/KaleyraVideoSDK":{"abstract":[],"kind":"symbol","type":"topic","identifier":"doc:\/\/com.kaleyra.KaleyraVideoSDK\/documentation\/KaleyraVideoSDK","url":"\/documentation\/kaleyravideosdk","title":"KaleyraVideoSDK","role":"collection"},"doc://com.kaleyra.KaleyraVideoSDK/documentation/KaleyraVideoSDK/ChatViewController":{"identifier":"doc:\/\/com.kaleyra.KaleyraVideoSDK\/documentation\/KaleyraVideoSDK\/ChatViewController","kind":"symbol","type":"topic","fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"ChatViewController"}],"role":"symbol","navigatorTitle":[{"text":"ChatViewController","kind":"identifier"}],"abstract":[{"type":"text","text":"A view controller showing the user interface of a chat."}],"title":"ChatViewController","url":"\/documentation\/kaleyravideosdk\/chatviewcontroller"},"doc://com.kaleyra.KaleyraVideoSDK/documentation/KaleyraVideoSDK/ChatViewController/UIBarPositioningDelegate-Implementations":{"abstract":[],"url":"\/documentation\/kaleyravideosdk\/chatviewcontroller\/uibarpositioningdelegate-implementations","identifier":"doc:\/\/com.kaleyra.KaleyraVideoSDK\/documentation\/KaleyraVideoSDK\/ChatViewController\/UIBarPositioningDelegate-Implementations","title":"UIBarPositioningDelegate Implementations","role":"collectionGroup","kind":"article","type":"topic"},"doc://com.kaleyra.KaleyraVideoSDK/documentation/KaleyraVideoSDK/ChatViewController/position(for:)":{"role":"symbol","identifier":"doc:\/\/com.kaleyra.KaleyraVideoSDK\/documentation\/KaleyraVideoSDK\/ChatViewController\/position(for:)","navigatorTitle":[{"kind":"identifier","text":"positionForBar:"}],"title":"position(for:)","fragments":[{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"text":"position","kind":"identifier"},{"kind":"text","text":"("},{"text":"for","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:objc(pl)UIBarPositioning","text":"UIBarPositioning","kind":"typeIdentifier"},{"text":") -> ","kind":"text"},{"text":"UIBarPosition","preciseIdentifier":"c:@E@UIBarPosition","kind":"typeIdentifier"}],"url":"\/documentation\/kaleyravideosdk\/chatviewcontroller\/position(for:)","type":"topic","abstract":[],"kind":"symbol"}},"variantOverrides":[{"patch":[{"path":"\/identifier\/interfaceLanguage","op":"replace","value":"occ"},{"path":"\/metadata\/roleHeading","value":"Instance Method","op":"replace"},{"path":"\/metadata\/title","value":"positionForBar:","op":"replace"},{"value":"method","path":"\/metadata\/symbolKind","op":"replace"},{"op":"replace","value":[{"kind":"text","text":"- "},{"text":"positionForBar:","kind":"identifier"}],"path":"\/metadata\/fragments"},{"path":"\/topicSections","value":null,"op":"add"},{"op":"add","path":"\/relationshipsSections","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"path":"\/primaryContentSections\/0","op":"replace","value":{"kind":"declarations","declarations":[{"languages":["occ"],"platforms":["iOS"],"tokens":[{"text":"- (","kind":"text"},{"preciseIdentifier":"c:@E@UIBarPosition","text":"UIBarPosition","kind":"typeIdentifier"},{"text":") ","kind":"text"},{"kind":"identifier","text":"positionForBar:"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"id<UIBarPositioning>","preciseIdentifier":"c:Qoobjc(pl)UIBarPositioning"},{"text":") ","kind":"text"},{"kind":"internalParam","text":"bar"},{"text":";","kind":"text"}]}]}},{"value":"ChatViewController","op":"replace","path":"\/references\/doc:~1~1com.kaleyra.KaleyraVideoSDK~1documentation~1KaleyraVideoSDK~1ChatViewController\/title"},{"value":[{"kind":"identifier","text":"ChatViewController"}],"op":"replace","path":"\/references\/doc:~1~1com.kaleyra.KaleyraVideoSDK~1documentation~1KaleyraVideoSDK~1ChatViewController\/fragments"},{"path":"\/references\/doc:~1~1com.kaleyra.KaleyraVideoSDK~1documentation~1KaleyraVideoSDK~1ChatViewController~1position(for:)\/title","value":"positionForBar:","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1com.kaleyra.KaleyraVideoSDK~1documentation~1KaleyraVideoSDK~1ChatViewController~1position(for:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"positionForBar:"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}