{"topicSections":[{"title":"Instance Methods","identifiers":["doc:\/\/com.kaleyra.KaleyraVideoSDK\/documentation\/KaleyraVideoSDK\/ChatViewController\/position(for:)"],"generated":true}],"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/com.kaleyra.KaleyraVideoSDK\/documentation\/KaleyraVideoSDK\/ChatViewController\/UIBarPositioningDelegate-Implementations"},"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/kaleyravideosdk\/chatviewcontroller\/uibarpositioningdelegate-implementations"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/kaleyravideosdk\/chatviewcontroller\/uibarpositioningdelegate-implementations"]}],"sections":[],"schemaVersion":{"patch":0,"major":0,"minor":3},"metadata":{"title":"UIBarPositioningDelegate Implementations","roleHeading":"API Collection","role":"collectionGroup","modules":[{"name":"KaleyraVideoSDK"}]},"hierarchy":{"paths":[["doc:\/\/com.kaleyra.KaleyraVideoSDK\/documentation\/KaleyraVideoSDK","doc:\/\/com.kaleyra.KaleyraVideoSDK\/documentation\/KaleyraVideoSDK\/ChatViewController"]]},"kind":"article","references":{"doc://com.kaleyra.KaleyraVideoSDK/documentation/KaleyraVideoSDK":{"kind":"symbol","type":"topic","url":"\/documentation\/kaleyravideosdk","abstract":[],"role":"collection","identifier":"doc:\/\/com.kaleyra.KaleyraVideoSDK\/documentation\/KaleyraVideoSDK","title":"KaleyraVideoSDK"},"doc://com.kaleyra.KaleyraVideoSDK/documentation/KaleyraVideoSDK/ChatViewController/position(for:)":{"abstract":[],"fragments":[{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"text":"position","kind":"identifier"},{"text":"(","kind":"text"},{"text":"for","kind":"externalParam"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"UIBarPositioning","preciseIdentifier":"c:objc(pl)UIBarPositioning"},{"kind":"text","text":") -> "},{"text":"UIBarPosition","kind":"typeIdentifier","preciseIdentifier":"c:@E@UIBarPosition"}],"kind":"symbol","type":"topic","title":"position(for:)","role":"symbol","identifier":"doc:\/\/com.kaleyra.KaleyraVideoSDK\/documentation\/KaleyraVideoSDK\/ChatViewController\/position(for:)","navigatorTitle":[{"kind":"identifier","text":"positionForBar:"}],"url":"\/documentation\/kaleyravideosdk\/chatviewcontroller\/position(for:)"},"doc://com.kaleyra.KaleyraVideoSDK/documentation/KaleyraVideoSDK/ChatViewController":{"abstract":[{"type":"text","text":"A view controller showing the user interface of a chat."}],"fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"kind":"identifier","text":"ChatViewController"}],"kind":"symbol","type":"topic","title":"ChatViewController","role":"symbol","identifier":"doc:\/\/com.kaleyra.KaleyraVideoSDK\/documentation\/KaleyraVideoSDK\/ChatViewController","navigatorTitle":[{"kind":"identifier","text":"ChatViewController"}],"url":"\/documentation\/kaleyravideosdk\/chatviewcontroller"}},"variantOverrides":[{"patch":[{"op":"replace","value":"occ","path":"\/identifier\/interfaceLanguage"},{"value":[{"identifiers":["doc:\/\/com.kaleyra.KaleyraVideoSDK\/documentation\/KaleyraVideoSDK\/ChatViewController\/position(for:)"],"generated":true,"title":"Instance Methods"}],"op":"replace","path":"\/topicSections"},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/references\/doc:~1~1com.kaleyra.KaleyraVideoSDK~1documentation~1KaleyraVideoSDK~1ChatViewController~1position(for:)\/title","value":"positionForBar:"},{"op":"replace","path":"\/references\/doc:~1~1com.kaleyra.KaleyraVideoSDK~1documentation~1KaleyraVideoSDK~1ChatViewController~1position(for:)\/fragments","value":[{"kind":"text","text":"- "},{"text":"positionForBar:","kind":"identifier"}]},{"path":"\/references\/doc:~1~1com.kaleyra.KaleyraVideoSDK~1documentation~1KaleyraVideoSDK~1ChatViewController\/title","value":"ChatViewController","op":"replace"},{"path":"\/references\/doc:~1~1com.kaleyra.KaleyraVideoSDK~1documentation~1KaleyraVideoSDK~1ChatViewController\/fragments","op":"replace","value":[{"kind":"identifier","text":"ChatViewController"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}