{"sections":[],"metadata":{"modules":[{"name":"KaleyraVideoBroadcastExtension"}],"title":"KaleyraVideoBroadcastExtension","externalID":"KaleyraVideoBroadcastExtension","symbolKind":"module","role":"collection","roleHeading":"Framework"},"topicSections":[{"title":"Classes","identifiers":["doc:\/\/com.kaleyra.KaleyraVideoBroadcastExtension\/documentation\/KaleyraVideoBroadcastExtension\/BroadcastExtension"]},{"title":"Structures","identifiers":["doc:\/\/com.kaleyra.KaleyraVideoBroadcastExtension\/documentation\/KaleyraVideoBroadcastExtension\/AppGroupIdentifier"]},{"title":"Enumerations","identifiers":["doc:\/\/com.kaleyra.KaleyraVideoBroadcastExtension\/documentation\/KaleyraVideoBroadcastExtension\/LogFlag","doc:\/\/com.kaleyra.KaleyraVideoBroadcastExtension\/documentation\/KaleyraVideoBroadcastExtension\/LogLevel"]}],"schemaVersion":{"patch":0,"minor":3,"major":0},"hierarchy":{"paths":[[]]},"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/kaleyravideobroadcastextension"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/kaleyravideobroadcastextension"]}],"kind":"symbol","identifier":{"url":"doc:\/\/com.kaleyra.KaleyraVideoBroadcastExtension\/documentation\/KaleyraVideoBroadcastExtension","interfaceLanguage":"swift"},"references":{"doc://com.kaleyra.KaleyraVideoBroadcastExtension/documentation/KaleyraVideoBroadcastExtension/KaleyraVideoBroadcastExtensionVersionString":{"kind":"symbol","type":"topic","role":"symbol","title":"KaleyraVideoBroadcastExtensionVersionString","fragments":[{"kind":"identifier","text":"KaleyraVideoBroadcastExtensionVersionString"}],"identifier":"doc:\/\/com.kaleyra.KaleyraVideoBroadcastExtension\/documentation\/KaleyraVideoBroadcastExtension\/KaleyraVideoBroadcastExtensionVersionString","abstract":[{"text":"Project version string for KaleyraVideoBroadcastExtension.","type":"text"}],"url":"\/documentation\/kaleyravideobroadcastextension\/kaleyravideobroadcastextensionversionstring"},"doc://com.kaleyra.KaleyraVideoBroadcastExtension/documentation/KaleyraVideoBroadcastExtension/LogFlag":{"identifier":"doc:\/\/com.kaleyra.KaleyraVideoBroadcastExtension\/documentation\/KaleyraVideoBroadcastExtension\/LogFlag","type":"topic","role":"symbol","title":"LogFlag","abstract":[{"type":"text","text":"Log flags."}],"fragments":[{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"text":"LogFlag","kind":"identifier"}],"kind":"symbol","url":"\/documentation\/kaleyravideobroadcastextension\/logflag","navigatorTitle":[{"kind":"identifier","text":"LogFlag"}]},"doc://com.kaleyra.KaleyraVideoBroadcastExtension/documentation/KaleyraVideoBroadcastExtension/AppGroupIdentifier":{"fragments":[{"text":"struct","kind":"keyword"},{"text":" ","kind":"text"},{"text":"AppGroupIdentifier","kind":"identifier"}],"type":"topic","title":"AppGroupIdentifier","abstract":[{"text":"A value representing an App group identifier","type":"text"}],"url":"\/documentation\/kaleyravideobroadcastextension\/appgroupidentifier","kind":"symbol","navigatorTitle":[{"kind":"identifier","text":"AppGroupIdentifier"}],"identifier":"doc:\/\/com.kaleyra.KaleyraVideoBroadcastExtension\/documentation\/KaleyraVideoBroadcastExtension\/AppGroupIdentifier","role":"symbol"},"doc://com.kaleyra.KaleyraVideoBroadcastExtension/documentation/KaleyraVideoBroadcastExtension/BroadcastExtension":{"type":"topic","kind":"symbol","role":"symbol","fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"kind":"identifier","text":"BroadcastExtension"}],"navigatorTitle":[{"text":"BroadcastExtension","kind":"identifier"}],"identifier":"doc:\/\/com.kaleyra.KaleyraVideoBroadcastExtension\/documentation\/KaleyraVideoBroadcastExtension\/BroadcastExtension","abstract":[{"type":"text","text":"A class responsible for handling a broadcast session with the Kaleyra Video platform."}],"title":"BroadcastExtension","url":"\/documentation\/kaleyravideobroadcastextension\/broadcastextension"},"doc://com.kaleyra.KaleyraVideoBroadcastExtension/documentation/KaleyraVideoBroadcastExtension":{"title":"KaleyraVideoBroadcastExtension","url":"\/documentation\/kaleyravideobroadcastextension","role":"collection","identifier":"doc:\/\/com.kaleyra.KaleyraVideoBroadcastExtension\/documentation\/KaleyraVideoBroadcastExtension","kind":"symbol","abstract":[],"type":"topic"},"doc://com.kaleyra.KaleyraVideoBroadcastExtension/documentation/KaleyraVideoBroadcastExtension/KaleyraVideoBroadcastExtensionVersionNumber":{"type":"topic","kind":"symbol","identifier":"doc:\/\/com.kaleyra.KaleyraVideoBroadcastExtension\/documentation\/KaleyraVideoBroadcastExtension\/KaleyraVideoBroadcastExtensionVersionNumber","url":"\/documentation\/kaleyravideobroadcastextension\/kaleyravideobroadcastextensionversionnumber","title":"KaleyraVideoBroadcastExtensionVersionNumber","fragments":[{"text":"KaleyraVideoBroadcastExtensionVersionNumber","kind":"identifier"}],"role":"symbol","abstract":[{"text":"Project version number for KaleyraVideoBroadcastExtension.","type":"text"}]},"doc://com.kaleyra.KaleyraVideoBroadcastExtension/documentation/KaleyraVideoBroadcastExtension/LogLevel":{"navigatorTitle":[{"text":"LogLevel","kind":"identifier"}],"role":"symbol","identifier":"doc:\/\/com.kaleyra.KaleyraVideoBroadcastExtension\/documentation\/KaleyraVideoBroadcastExtension\/LogLevel","kind":"symbol","url":"\/documentation\/kaleyravideobroadcastextension\/loglevel","abstract":[{"type":"text","text":"Log levels are used to filter out logs."}],"title":"LogLevel","type":"topic","fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"LogLevel"}]}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/topicSections","value":[{"title":"Variables","identifiers":["doc:\/\/com.kaleyra.KaleyraVideoBroadcastExtension\/documentation\/KaleyraVideoBroadcastExtension\/KaleyraVideoBroadcastExtensionVersionNumber","doc:\/\/com.kaleyra.KaleyraVideoBroadcastExtension\/documentation\/KaleyraVideoBroadcastExtension\/KaleyraVideoBroadcastExtensionVersionString"]}]},{"path":"\/relationshipsSections","value":null,"op":"add"},{"value":null,"op":"add","path":"\/seeAlsoSections"}],"traits":[{"interfaceLanguage":"occ"}]}]}