{"topicSections":[{"title":"Instance Methods","identifiers":["doc:\/\/com.kaleyra.KaleyraVideoSDK\/documentation\/KaleyraVideoSDK\/CallWindow\/set(rootViewController:animated:completion:)"]}],"metadata":{"roleHeading":"Class","navigatorTitle":[{"kind":"identifier","text":"CallWindow"}],"platforms":[{"deprecated":false,"beta":false,"name":"iOS","unavailable":false,"introducedAt":"15.0"}],"symbolKind":"class","fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"kind":"identifier","text":"CallWindow"}],"externalID":"c:@M@KaleyraVideoSDK@objc(cs)CallWindow","role":"symbol","modules":[{"name":"KaleyraVideoSDK"}],"title":"CallWindow"},"hierarchy":{"paths":[["doc:\/\/com.kaleyra.KaleyraVideoSDK\/documentation\/KaleyraVideoSDK"]]},"relationshipsSections":[{"identifiers":["doc:\/\/com.kaleyra.KaleyraVideoSDK\/objc(cs)UIWindow"],"type":"inheritsFrom","kind":"relationships","title":"Inherits From"},{"identifiers":["doc:\/\/com.kaleyra.KaleyraVideoSDK\/objc(pl)NSCoding","doc:\/\/com.kaleyra.KaleyraVideoSDK\/17KaleyraFoundation21PropertyProxyProviderP","doc:\/\/com.kaleyra.KaleyraVideoSDK\/17KaleyraFoundation18SubscriptionsOwnerP","doc:\/\/com.kaleyra.KaleyraVideoSDK\/19KaleyraUIComponents13ConstrainableP","doc:\/\/com.kaleyra.KaleyraVideoSDK\/19KaleyraUIComponents22RemovableFromSuperviewP","doc:\/\/com.kaleyra.KaleyraVideoSDK\/objc(pl)NSObject","doc:\/\/com.kaleyra.KaleyraVideoSDK\/objc(pl)CALayerDelegate","doc:\/\/com.kaleyra.KaleyraVideoSDK\/s7CVarArgP","doc:\/\/com.kaleyra.KaleyraVideoSDK\/s28CustomDebugStringConvertibleP","doc:\/\/com.kaleyra.KaleyraVideoSDK\/s23CustomStringConvertibleP","doc:\/\/com.kaleyra.KaleyraVideoSDK\/SQ","doc:\/\/com.kaleyra.KaleyraVideoSDK\/SH","doc:\/\/com.kaleyra.KaleyraVideoSDK\/s8SendableP","doc:\/\/com.kaleyra.KaleyraVideoSDK\/objc(pl)UIAccessibilityIdentification","doc:\/\/com.kaleyra.KaleyraVideoSDK\/objc(pl)UIActivityItemsConfigurationProviding","doc:\/\/com.kaleyra.KaleyraVideoSDK\/objc(pl)UIAppearance","doc:\/\/com.kaleyra.KaleyraVideoSDK\/objc(pl)UIAppearanceContainer","doc:\/\/com.kaleyra.KaleyraVideoSDK\/objc(pl)UICoordinateSpace","doc:\/\/com.kaleyra.KaleyraVideoSDK\/objc(pl)UIDynamicItem","doc:\/\/com.kaleyra.KaleyraVideoSDK\/objc(pl)UIFocusEnvironment","doc:\/\/com.kaleyra.KaleyraVideoSDK\/objc(pl)UIFocusItem","doc:\/\/com.kaleyra.KaleyraVideoSDK\/objc(pl)UIFocusItemContainer","doc:\/\/com.kaleyra.KaleyraVideoSDK\/objc(pl)UILargeContentViewerItem","doc:\/\/com.kaleyra.KaleyraVideoSDK\/objc(pl)UIPasteConfigurationSupporting","doc:\/\/com.kaleyra.KaleyraVideoSDK\/objc(pl)UIPopoverPresentationControllerSourceItem","doc:\/\/com.kaleyra.KaleyraVideoSDK\/objc(pl)UIResponderStandardEditActions","doc:\/\/com.kaleyra.KaleyraVideoSDK\/5UIKit23UITraitChangeObservableP","doc:\/\/com.kaleyra.KaleyraVideoSDK\/objc(pl)UITraitEnvironment","doc:\/\/com.kaleyra.KaleyraVideoSDK\/objc(pl)UIUserActivityRestoring"],"title":"Conforms To","type":"conformsTo","kind":"relationships"}],"primaryContentSections":[{"kind":"declarations","declarations":[{"platforms":["iOS"],"tokens":[{"text":"final","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"text":"CallWindow","kind":"identifier"}],"languages":["swift"]}]},{"kind":"content","content":[{"level":2,"text":"Overview","type":"heading","anchor":"overview"},{"inlineContent":[{"type":"text","text":"You typically use an instance of this class when you want to present a "},{"type":"reference","isActive":true,"identifier":"doc:\/\/com.kaleyra.KaleyraVideoSDK\/documentation\/KaleyraVideoSDK\/CallViewController"},{"type":"text","text":" in front of your app contents."},{"text":" ","type":"text"},{"text":"Its ","type":"text"},{"identifier":"doc:\/\/com.kaleyra.KaleyraVideoSDK\/documentation\/KaleyraVideoSDK\/CallWindow\/windowLevel","type":"reference","isActive":true},{"type":"text","text":" is fixed and cannot be changed"}],"type":"paragraph"},{"content":[{"inlineContent":[{"text":"3.0.0","type":"text"}],"type":"paragraph"}],"style":"note","name":"Since","type":"aside"}]}],"abstract":[{"type":"text","text":"A window presenting its root view controller animated."}],"kind":"symbol","variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/kaleyravideosdk\/callwindow"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/kaleyravideosdk\/callwindow"]}],"sections":[],"identifier":{"url":"doc:\/\/com.kaleyra.KaleyraVideoSDK\/documentation\/KaleyraVideoSDK\/CallWindow","interfaceLanguage":"swift"},"schemaVersion":{"minor":3,"major":0,"patch":0},"references":{"doc://com.kaleyra.KaleyraVideoSDK/objc(pl)UIFocusItem":{"type":"unresolvable","identifier":"doc:\/\/com.kaleyra.KaleyraVideoSDK\/objc(pl)UIFocusItem","title":"UIKit.UIFocusItem"},"doc://com.kaleyra.KaleyraVideoSDK/documentation/KaleyraVideoSDK":{"abstract":[],"kind":"symbol","type":"topic","identifier":"doc:\/\/com.kaleyra.KaleyraVideoSDK\/documentation\/KaleyraVideoSDK","url":"\/documentation\/kaleyravideosdk","title":"KaleyraVideoSDK","role":"collection"},"doc://com.kaleyra.KaleyraVideoSDK/objc(pl)UIPasteConfigurationSupporting":{"type":"unresolvable","identifier":"doc:\/\/com.kaleyra.KaleyraVideoSDK\/objc(pl)UIPasteConfigurationSupporting","title":"UIKit.UIPasteConfigurationSupporting"},"doc://com.kaleyra.KaleyraVideoSDK/documentation/KaleyraVideoSDK/CallWindow/initWithWindowScene:":{"navigatorTitle":[{"kind":"identifier","text":"initWithWindowScene:"}],"identifier":"doc:\/\/com.kaleyra.KaleyraVideoSDK\/documentation\/KaleyraVideoSDK\/CallWindow\/initWithWindowScene:","type":"topic","title":"initWithWindowScene:","fragments":[{"text":"- ","kind":"text"},{"kind":"identifier","text":"initWithWindowScene:"}],"kind":"symbol","url":"\/documentation\/kaleyravideosdk\/callwindow\/initwithwindowscene:","abstract":[],"role":"symbol"},"doc://com.kaleyra.KaleyraVideoSDK/objc(pl)UICoordinateSpace":{"identifier":"doc:\/\/com.kaleyra.KaleyraVideoSDK\/objc(pl)UICoordinateSpace","type":"unresolvable","title":"UIKit.UICoordinateSpace"},"doc://com.kaleyra.KaleyraVideoSDK/documentation/KaleyraVideoSDK/CallWindow/set(rootViewController:animated:completion:)":{"type":"topic","url":"\/documentation\/kaleyravideosdk\/callwindow\/set(rootviewcontroller:animated:completion:)","title":"set(rootViewController:animated:completion:)","abstract":[{"text":"Sets the root view controller to the value provided as argument animated when the ","type":"text"},{"type":"codeVoice","code":"animated"},{"type":"text","text":" flag is true."}],"kind":"symbol","role":"symbol","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"text":"set","kind":"identifier"},{"text":"(","kind":"text"},{"text":"rootViewController","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:objc(cs)UIViewController","text":"UIViewController","kind":"typeIdentifier"},{"kind":"text","text":"?, "},{"text":"animated","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:Sb","text":"Bool","kind":"typeIdentifier"},{"kind":"text","text":", "},{"text":"completion","kind":"externalParam"},{"kind":"text","text":": (("},{"text":"Bool","preciseIdentifier":"s:Sb","kind":"typeIdentifier"},{"text":") -> ","kind":"text"},{"preciseIdentifier":"s:s4Voida","text":"Void","kind":"typeIdentifier"},{"kind":"text","text":")?)"}],"identifier":"doc:\/\/com.kaleyra.KaleyraVideoSDK\/documentation\/KaleyraVideoSDK\/CallWindow\/set(rootViewController:animated:completion:)"},"doc://com.kaleyra.KaleyraVideoSDK/objc(pl)UIFocusItemContainer":{"title":"UIKit.UIFocusItemContainer","type":"unresolvable","identifier":"doc:\/\/com.kaleyra.KaleyraVideoSDK\/objc(pl)UIFocusItemContainer"},"doc://com.kaleyra.KaleyraVideoSDK/objc(pl)UIAppearance":{"title":"UIKit.UIAppearance","type":"unresolvable","identifier":"doc:\/\/com.kaleyra.KaleyraVideoSDK\/objc(pl)UIAppearance"},"doc://com.kaleyra.KaleyraVideoSDK/documentation/KaleyraVideoSDK/CallWindow/windowLevel":{"type":"topic","url":"\/documentation\/kaleyravideosdk\/callwindow\/windowlevel","title":"windowLevel","abstract":[],"fragments":[{"kind":"identifier","text":"windowLevel"}],"role":"symbol","kind":"symbol","identifier":"doc:\/\/com.kaleyra.KaleyraVideoSDK\/documentation\/KaleyraVideoSDK\/CallWindow\/windowLevel"},"doc://com.kaleyra.KaleyraVideoSDK/SH":{"title":"Swift.Hashable","type":"unresolvable","identifier":"doc:\/\/com.kaleyra.KaleyraVideoSDK\/SH"},"doc://com.kaleyra.KaleyraVideoSDK/objc(cs)UIWindow":{"title":"UIWindow","type":"unresolvable","identifier":"doc:\/\/com.kaleyra.KaleyraVideoSDK\/objc(cs)UIWindow"},"doc://com.kaleyra.KaleyraVideoSDK/documentation/KaleyraVideoSDK/CallWindow/initWithCoder:":{"identifier":"doc:\/\/com.kaleyra.KaleyraVideoSDK\/documentation\/KaleyraVideoSDK\/CallWindow\/initWithCoder:","type":"topic","role":"symbol","fragments":[{"kind":"text","text":"- "},{"kind":"identifier","text":"initWithCoder:"}],"title":"initWithCoder:","abstract":[],"navigatorTitle":[{"text":"initWithCoder:","kind":"identifier"}],"kind":"symbol","url":"\/documentation\/kaleyravideosdk\/callwindow\/initwithcoder:"},"doc://com.kaleyra.KaleyraVideoSDK/objc(pl)UIAppearanceContainer":{"title":"UIKit.UIAppearanceContainer","type":"unresolvable","identifier":"doc:\/\/com.kaleyra.KaleyraVideoSDK\/objc(pl)UIAppearanceContainer"},"doc://com.kaleyra.KaleyraVideoSDK/objc(pl)NSCoding":{"title":"Foundation.NSCoding","type":"unresolvable","identifier":"doc:\/\/com.kaleyra.KaleyraVideoSDK\/objc(pl)NSCoding"},"doc://com.kaleyra.KaleyraVideoSDK/documentation/KaleyraVideoSDK/CallWindow/initWithFrame:":{"identifier":"doc:\/\/com.kaleyra.KaleyraVideoSDK\/documentation\/KaleyraVideoSDK\/CallWindow\/initWithFrame:","url":"\/documentation\/kaleyravideosdk\/callwindow\/initwithframe:","fragments":[{"kind":"text","text":"- "},{"kind":"identifier","text":"initWithFrame:"}],"title":"initWithFrame:","type":"topic","abstract":[],"role":"symbol","navigatorTitle":[{"kind":"identifier","text":"initWithFrame:"}],"kind":"symbol"},"doc://com.kaleyra.KaleyraVideoSDK/s23CustomStringConvertibleP":{"title":"Swift.CustomStringConvertible","type":"unresolvable","identifier":"doc:\/\/com.kaleyra.KaleyraVideoSDK\/s23CustomStringConvertibleP"},"doc://com.kaleyra.KaleyraVideoSDK/s7CVarArgP":{"title":"Swift.CVarArg","identifier":"doc:\/\/com.kaleyra.KaleyraVideoSDK\/s7CVarArgP","type":"unresolvable"},"doc://com.kaleyra.KaleyraVideoSDK/objc(pl)UIPopoverPresentationControllerSourceItem":{"title":"UIKit.UIPopoverPresentationControllerSourceItem","identifier":"doc:\/\/com.kaleyra.KaleyraVideoSDK\/objc(pl)UIPopoverPresentationControllerSourceItem","type":"unresolvable"},"doc://com.kaleyra.KaleyraVideoSDK/19KaleyraUIComponents22RemovableFromSuperviewP":{"title":"KaleyraUIComponents.RemovableFromSuperview","identifier":"doc:\/\/com.kaleyra.KaleyraVideoSDK\/19KaleyraUIComponents22RemovableFromSuperviewP","type":"unresolvable"},"doc://com.kaleyra.KaleyraVideoSDK/17KaleyraFoundation21PropertyProxyProviderP":{"title":"KaleyraFoundation.PropertyProxyProvider","identifier":"doc:\/\/com.kaleyra.KaleyraVideoSDK\/17KaleyraFoundation21PropertyProxyProviderP","type":"unresolvable"},"doc://com.kaleyra.KaleyraVideoSDK/documentation/KaleyraVideoSDK/CallWindow":{"identifier":"doc:\/\/com.kaleyra.KaleyraVideoSDK\/documentation\/KaleyraVideoSDK\/CallWindow","type":"topic","role":"symbol","fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"text":"CallWindow","kind":"identifier"}],"title":"CallWindow","abstract":[{"text":"A window presenting its root view controller animated.","type":"text"}],"navigatorTitle":[{"kind":"identifier","text":"CallWindow"}],"kind":"symbol","url":"\/documentation\/kaleyravideosdk\/callwindow"},"doc://com.kaleyra.KaleyraVideoSDK/objc(pl)UIFocusEnvironment":{"title":"UIKit.UIFocusEnvironment","identifier":"doc:\/\/com.kaleyra.KaleyraVideoSDK\/objc(pl)UIFocusEnvironment","type":"unresolvable"},"doc://com.kaleyra.KaleyraVideoSDK/objc(pl)NSObject":{"title":"ObjectiveC.NSObjectProtocol","identifier":"doc:\/\/com.kaleyra.KaleyraVideoSDK\/objc(pl)NSObject","type":"unresolvable"},"doc://com.kaleyra.KaleyraVideoSDK/objc(pl)CALayerDelegate":{"title":"QuartzCore.CALayerDelegate","identifier":"doc:\/\/com.kaleyra.KaleyraVideoSDK\/objc(pl)CALayerDelegate","type":"unresolvable"},"doc://com.kaleyra.KaleyraVideoSDK/documentation/KaleyraVideoSDK/CallWindow/hitTest:withEvent:":{"kind":"symbol","fragments":[{"text":"- ","kind":"text"},{"text":"hitTest:withEvent:","kind":"identifier"}],"url":"\/documentation\/kaleyravideosdk\/callwindow\/hittest:withevent:","type":"topic","role":"symbol","title":"hitTest:withEvent:","navigatorTitle":[{"kind":"identifier","text":"hitTest:withEvent:"}],"identifier":"doc:\/\/com.kaleyra.KaleyraVideoSDK\/documentation\/KaleyraVideoSDK\/CallWindow\/hitTest:withEvent:","abstract":[]},"doc://com.kaleyra.KaleyraVideoSDK/s8SendableP":{"title":"Swift.Sendable","identifier":"doc:\/\/com.kaleyra.KaleyraVideoSDK\/s8SendableP","type":"unresolvable"},"doc://com.kaleyra.KaleyraVideoSDK/5UIKit23UITraitChangeObservableP":{"title":"UIKit.UITraitChangeObservable","identifier":"doc:\/\/com.kaleyra.KaleyraVideoSDK\/5UIKit23UITraitChangeObservableP","type":"unresolvable"},"doc://com.kaleyra.KaleyraVideoSDK/documentation/KaleyraVideoSDK/CallViewController":{"role":"symbol","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"CallViewController","kind":"identifier"}],"navigatorTitle":[{"text":"CallViewController","kind":"identifier"}],"type":"topic","kind":"symbol","identifier":"doc:\/\/com.kaleyra.KaleyraVideoSDK\/documentation\/KaleyraVideoSDK\/CallViewController","abstract":[{"text":"A view controller showing a call user interface","type":"text"}],"title":"CallViewController","url":"\/documentation\/kaleyravideosdk\/callviewcontroller"},"doc://com.kaleyra.KaleyraVideoSDK/SQ":{"title":"Swift.Equatable","identifier":"doc:\/\/com.kaleyra.KaleyraVideoSDK\/SQ","type":"unresolvable"},"doc://com.kaleyra.KaleyraVideoSDK/objc(pl)UIResponderStandardEditActions":{"title":"UIKit.UIResponderStandardEditActions","identifier":"doc:\/\/com.kaleyra.KaleyraVideoSDK\/objc(pl)UIResponderStandardEditActions","type":"unresolvable"},"doc://com.kaleyra.KaleyraVideoSDK/objc(pl)UIUserActivityRestoring":{"title":"UIKit.UIUserActivityRestoring","identifier":"doc:\/\/com.kaleyra.KaleyraVideoSDK\/objc(pl)UIUserActivityRestoring","type":"unresolvable"},"doc://com.kaleyra.KaleyraVideoSDK/objc(pl)UIAccessibilityIdentification":{"title":"UIKit.UIAccessibilityIdentification","identifier":"doc:\/\/com.kaleyra.KaleyraVideoSDK\/objc(pl)UIAccessibilityIdentification","type":"unresolvable"},"doc://com.kaleyra.KaleyraVideoSDK/s28CustomDebugStringConvertibleP":{"title":"Swift.CustomDebugStringConvertible","identifier":"doc:\/\/com.kaleyra.KaleyraVideoSDK\/s28CustomDebugStringConvertibleP","type":"unresolvable"},"doc://com.kaleyra.KaleyraVideoSDK/19KaleyraUIComponents13ConstrainableP":{"title":"KaleyraUIComponents.Constrainable","identifier":"doc:\/\/com.kaleyra.KaleyraVideoSDK\/19KaleyraUIComponents13ConstrainableP","type":"unresolvable"},"doc://com.kaleyra.KaleyraVideoSDK/objc(pl)UIDynamicItem":{"type":"unresolvable","identifier":"doc:\/\/com.kaleyra.KaleyraVideoSDK\/objc(pl)UIDynamicItem","title":"UIKit.UIDynamicItem"},"doc://com.kaleyra.KaleyraVideoSDK/objc(pl)UIActivityItemsConfigurationProviding":{"type":"unresolvable","identifier":"doc:\/\/com.kaleyra.KaleyraVideoSDK\/objc(pl)UIActivityItemsConfigurationProviding","title":"UIKit.UIActivityItemsConfigurationProviding"},"doc://com.kaleyra.KaleyraVideoSDK/17KaleyraFoundation18SubscriptionsOwnerP":{"type":"unresolvable","identifier":"doc:\/\/com.kaleyra.KaleyraVideoSDK\/17KaleyraFoundation18SubscriptionsOwnerP","title":"KaleyraFoundation.SubscriptionsOwner"},"doc://com.kaleyra.KaleyraVideoSDK/objc(pl)UITraitEnvironment":{"type":"unresolvable","identifier":"doc:\/\/com.kaleyra.KaleyraVideoSDK\/objc(pl)UITraitEnvironment","title":"UIKit.UITraitEnvironment"},"doc://com.kaleyra.KaleyraVideoSDK/objc(pl)UILargeContentViewerItem":{"type":"unresolvable","identifier":"doc:\/\/com.kaleyra.KaleyraVideoSDK\/objc(pl)UILargeContentViewerItem","title":"UIKit.UILargeContentViewerItem"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"path":"\/identifier\/interfaceLanguage","value":"occ","op":"replace"},{"path":"\/metadata\/platforms","op":"replace","value":[{"deprecated":false,"name":"iOS","introducedAt":"15.0","unavailable":false,"beta":false}]},{"op":"replace","path":"\/metadata\/roleHeading","value":"Class"},{"op":"replace","value":"CallWindow","path":"\/metadata\/title"},{"op":"replace","path":"\/metadata\/symbolKind","value":"class"},{"value":[{"kind":"identifier","text":"CallWindow"}],"op":"replace","path":"\/metadata\/fragments"},{"path":"\/metadata\/navigatorTitle","op":"replace","value":[{"text":"CallWindow","kind":"identifier"}]},{"path":"\/topicSections","value":[{"title":"Instance Properties","identifiers":["doc:\/\/com.kaleyra.KaleyraVideoSDK\/documentation\/KaleyraVideoSDK\/CallWindow\/windowLevel"]},{"title":"Instance Methods","identifiers":["doc:\/\/com.kaleyra.KaleyraVideoSDK\/documentation\/KaleyraVideoSDK\/CallWindow\/hitTest:withEvent:","doc:\/\/com.kaleyra.KaleyraVideoSDK\/documentation\/KaleyraVideoSDK\/CallWindow\/initWithCoder:","doc:\/\/com.kaleyra.KaleyraVideoSDK\/documentation\/KaleyraVideoSDK\/CallWindow\/initWithFrame:","doc:\/\/com.kaleyra.KaleyraVideoSDK\/documentation\/KaleyraVideoSDK\/CallWindow\/initWithWindowScene:"]}],"op":"replace"},{"op":"replace","value":[{"kind":"relationships","identifiers":["doc:\/\/com.kaleyra.KaleyraVideoSDK\/objc(cs)UIWindow"],"title":"Inherits From","type":"inheritsFrom"}],"path":"\/relationshipsSections"},{"path":"\/seeAlsoSections","value":null,"op":"add"},{"op":"replace","value":{"declarations":[{"platforms":["iOS"],"languages":["occ"],"tokens":[{"kind":"keyword","text":"@interface"},{"text":" ","kind":"text"},{"text":"CallWindow","kind":"identifier"},{"text":" : ","kind":"text"},{"text":"UIWindow","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)UIWindow"}]}],"kind":"declarations"},"path":"\/primaryContentSections\/0"},{"value":"CallWindow","path":"\/references\/doc:~1~1com.kaleyra.KaleyraVideoSDK~1documentation~1KaleyraVideoSDK~1CallWindow\/title","op":"replace"},{"path":"\/references\/doc:~1~1com.kaleyra.KaleyraVideoSDK~1documentation~1KaleyraVideoSDK~1CallWindow\/fragments","value":[{"text":"CallWindow","kind":"identifier"}],"op":"replace"},{"path":"\/references\/doc:~1~1com.kaleyra.KaleyraVideoSDK~1documentation~1KaleyraVideoSDK~1CallViewController\/title","value":"CallViewController","op":"replace"},{"path":"\/references\/doc:~1~1com.kaleyra.KaleyraVideoSDK~1documentation~1KaleyraVideoSDK~1CallViewController\/fragments","op":"replace","value":[{"kind":"identifier","text":"CallViewController"}]}]}]}