{"variants":[{"paths":["\/documentation\/kaleyravideosdk\/callviewcontroller"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/kaleyravideosdk\/callviewcontroller"],"traits":[{"interfaceLanguage":"occ"}]}],"topicSections":[{"identifiers":["doc:\/\/com.kaleyra.KaleyraVideoSDK\/documentation\/KaleyraVideoSDK\/CallViewController\/Configuration"],"title":"Structures"},{"identifiers":["doc:\/\/com.kaleyra.KaleyraVideoSDK\/documentation\/KaleyraVideoSDK\/CallViewController\/init(call:configuration:)"],"title":"Initializers"},{"title":"Instance Properties","identifiers":["doc:\/\/com.kaleyra.KaleyraVideoSDK\/documentation\/KaleyraVideoSDK\/CallViewController\/buttonsProvider","doc:\/\/com.kaleyra.KaleyraVideoSDK\/documentation\/KaleyraVideoSDK\/CallViewController\/delegate"]},{"title":"Instance Methods","identifiers":["doc:\/\/com.kaleyra.KaleyraVideoSDK\/documentation\/KaleyraVideoSDK\/CallViewController\/change(presentationMode:animated:completion:)","doc:\/\/com.kaleyra.KaleyraVideoSDK\/documentation\/KaleyraVideoSDK\/CallViewController\/dismiss(message:)","doc:\/\/com.kaleyra.KaleyraVideoSDK\/documentation\/KaleyraVideoSDK\/CallViewController\/present(message:)"]}],"metadata":{"navigatorTitle":[{"text":"CallViewController","kind":"identifier"}],"modules":[{"name":"KaleyraVideoSDK"}],"externalID":"c:@M@KaleyraVideoSDK@objc(cs)CallViewController","role":"symbol","platforms":[{"deprecated":false,"beta":false,"introducedAt":"15.0","name":"iOS","unavailable":false}],"title":"CallViewController","symbolKind":"class","fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"kind":"identifier","text":"CallViewController"}],"roleHeading":"Class"},"sections":[],"primaryContentSections":[{"kind":"declarations","declarations":[{"platforms":["iOS"],"languages":["swift"],"tokens":[{"kind":"keyword","text":"final"},{"text":" ","kind":"text"},{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"CallViewController"}]}]},{"content":[{"level":2,"type":"heading","anchor":"overview","text":"Overview"},{"inlineContent":[{"text":"When you want to present the user interface for a call you must create a ","type":"text"},{"type":"reference","identifier":"doc:\/\/com.kaleyra.KaleyraVideoSDK\/documentation\/KaleyraVideoSDK\/CallViewController","isActive":true},{"text":" providing it a call object and present it modally or embedded it in a ","type":"text"},{"type":"reference","isActive":true,"identifier":"doc:\/\/com.kaleyra.KaleyraVideoSDK\/documentation\/KaleyraVideoSDK\/CallWindow"},{"type":"text","text":"."}],"type":"paragraph"},{"name":"Since","style":"note","type":"aside","content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"3.0.0"}]}]}],"kind":"content"}],"hierarchy":{"paths":[["doc:\/\/com.kaleyra.KaleyraVideoSDK\/documentation\/KaleyraVideoSDK"]]},"schemaVersion":{"major":0,"patch":0,"minor":3},"identifier":{"url":"doc:\/\/com.kaleyra.KaleyraVideoSDK\/documentation\/KaleyraVideoSDK\/CallViewController","interfaceLanguage":"swift"},"abstract":[{"type":"text","text":"A view controller showing a call user interface"}],"kind":"symbol","relationshipsSections":[{"title":"Inherits From","type":"inheritsFrom","identifiers":["doc:\/\/com.kaleyra.KaleyraVideoSDK\/objc(cs)UIViewController"],"kind":"relationships"},{"title":"Conforms To","kind":"relationships","type":"conformsTo","identifiers":["doc:\/\/com.kaleyra.KaleyraVideoSDK\/objc(pl)NSCoding","doc:\/\/com.kaleyra.KaleyraVideoSDK\/objc(pl)NSExtensionRequestHandling","doc:\/\/com.kaleyra.KaleyraVideoSDK\/17KaleyraFoundation21PropertyProxyProviderP","doc:\/\/com.kaleyra.KaleyraVideoSDK\/17KaleyraFoundation18SubscriptionsOwnerP","doc:\/\/com.kaleyra.KaleyraVideoSDK\/objc(pl)NSObject","doc:\/\/com.kaleyra.KaleyraVideoSDK\/s7CVarArgP","doc:\/\/com.kaleyra.KaleyraVideoSDK\/s28CustomDebugStringConvertibleP","doc:\/\/com.kaleyra.KaleyraVideoSDK\/s23CustomStringConvertibleP","doc:\/\/com.kaleyra.KaleyraVideoSDK\/SQ","doc:\/\/com.kaleyra.KaleyraVideoSDK\/SH","doc:\/\/com.kaleyra.KaleyraVideoSDK\/objc(pl)UIActivityItemsConfigurationProviding","doc:\/\/com.kaleyra.KaleyraVideoSDK\/objc(pl)UIAppearanceContainer","doc:\/\/com.kaleyra.KaleyraVideoSDK\/objc(pl)UIContentContainer","doc:\/\/com.kaleyra.KaleyraVideoSDK\/objc(pl)UIFocusEnvironment","doc:\/\/com.kaleyra.KaleyraVideoSDK\/objc(pl)UIPasteConfigurationSupporting","doc:\/\/com.kaleyra.KaleyraVideoSDK\/objc(pl)UIResponderStandardEditActions","doc:\/\/com.kaleyra.KaleyraVideoSDK\/objc(pl)UIStateRestoring","doc:\/\/com.kaleyra.KaleyraVideoSDK\/5UIKit23UITraitChangeObservableP","doc:\/\/com.kaleyra.KaleyraVideoSDK\/objc(pl)UITraitEnvironment","doc:\/\/com.kaleyra.KaleyraVideoSDK\/objc(pl)UIUserActivityRestoring"]}],"references":{"doc://com.kaleyra.KaleyraVideoSDK/documentation/KaleyraVideoSDK/CallViewController/viewWillAppear:":{"identifier":"doc:\/\/com.kaleyra.KaleyraVideoSDK\/documentation\/KaleyraVideoSDK\/CallViewController\/viewWillAppear:","abstract":[],"kind":"symbol","title":"viewWillAppear:","navigatorTitle":[{"text":"viewWillAppear:","kind":"identifier"}],"url":"\/documentation\/kaleyravideosdk\/callviewcontroller\/viewwillappear:","type":"topic","role":"symbol","fragments":[{"kind":"text","text":"- "},{"kind":"identifier","text":"viewWillAppear:"}]},"doc://com.kaleyra.KaleyraVideoSDK/documentation/KaleyraVideoSDK":{"abstract":[],"title":"KaleyraVideoSDK","role":"collection","type":"topic","kind":"symbol","identifier":"doc:\/\/com.kaleyra.KaleyraVideoSDK\/documentation\/KaleyraVideoSDK","url":"\/documentation\/kaleyravideosdk"},"doc://com.kaleyra.KaleyraVideoSDK/documentation/KaleyraVideoSDK/Call":{"url":"\/documentation\/kaleyravideosdk\/call","title":"Call","type":"topic","navigatorTitle":[{"kind":"identifier","text":"Call"}],"identifier":"doc:\/\/com.kaleyra.KaleyraVideoSDK\/documentation\/KaleyraVideoSDK\/Call","abstract":[{"text":"An object representing a Kaleyra Video VoIP call.","type":"text"}],"fragments":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"Call"}],"role":"symbol","kind":"symbol"},"doc://com.kaleyra.KaleyraVideoSDK/objc(pl)UIFocusEnvironment":{"type":"unresolvable","title":"UIKit.UIFocusEnvironment","identifier":"doc:\/\/com.kaleyra.KaleyraVideoSDK\/objc(pl)UIFocusEnvironment"},"doc://com.kaleyra.KaleyraVideoSDK/documentation/KaleyraVideoSDK/CallViewController/loadView":{"identifier":"doc:\/\/com.kaleyra.KaleyraVideoSDK\/documentation\/KaleyraVideoSDK\/CallViewController\/loadView","abstract":[],"kind":"symbol","title":"loadView","navigatorTitle":[{"text":"loadView","kind":"identifier"}],"url":"\/documentation\/kaleyravideosdk\/callviewcontroller\/loadview","type":"topic","role":"symbol","fragments":[{"kind":"text","text":"- "},{"kind":"identifier","text":"loadView"}]},"doc://com.kaleyra.KaleyraVideoSDK/documentation/KaleyraVideoSDK/CallViewController/buttonsProvider":{"identifier":"doc:\/\/com.kaleyra.KaleyraVideoSDK\/documentation\/KaleyraVideoSDK\/CallViewController\/buttonsProvider","abstract":[{"type":"text","text":"A custom supplied function allowing the host app to customise the buttons displayed during a call."}],"kind":"symbol","title":"buttonsProvider","url":"\/documentation\/kaleyravideosdk\/callviewcontroller\/buttonsprovider","type":"topic","role":"symbol","fragments":[{"kind":"keyword","text":"var"},{"text":" ","kind":"text"},{"kind":"identifier","text":"buttonsProvider"},{"kind":"text","text":": ((["},{"kind":"typeIdentifier","preciseIdentifier":"s:15KaleyraVideoSDK10CallButtonO","text":"CallButton"},{"text":"]) -> [","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"s:15KaleyraVideoSDK10CallButtonO","text":"CallButton"},{"kind":"text","text":"])?"}]},"doc://com.kaleyra.KaleyraVideoSDK/documentation/KaleyraVideoSDK/CallWindow":{"abstract":[{"type":"text","text":"A window presenting its root view controller animated."}],"url":"\/documentation\/kaleyravideosdk\/callwindow","type":"topic","navigatorTitle":[{"text":"CallWindow","kind":"identifier"}],"fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"CallWindow"}],"title":"CallWindow","identifier":"doc:\/\/com.kaleyra.KaleyraVideoSDK\/documentation\/KaleyraVideoSDK\/CallWindow","kind":"symbol","role":"symbol"},"doc://com.kaleyra.KaleyraVideoSDK/s28CustomDebugStringConvertibleP":{"identifier":"doc:\/\/com.kaleyra.KaleyraVideoSDK\/s28CustomDebugStringConvertibleP","type":"unresolvable","title":"Swift.CustomDebugStringConvertible"},"doc://com.kaleyra.KaleyraVideoSDK/documentation/KaleyraVideoSDK/CallViewController/change(presentationMode:animated:completion:)":{"identifier":"doc:\/\/com.kaleyra.KaleyraVideoSDK\/documentation\/KaleyraVideoSDK\/CallViewController\/change(presentationMode:animated:completion:)","abstract":[{"type":"text","text":"Invoke this method when you want to change the current "},{"code":"CallViewController.Confguration.PresentationMode","type":"codeVoice"},{"text":" of the call UI.","type":"text"}],"kind":"symbol","title":"change(presentationMode:animated:completion:)","url":"\/documentation\/kaleyravideosdk\/callviewcontroller\/change(presentationmode:animated:completion:)","type":"topic","role":"symbol","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"change"},{"text":"(","kind":"text"},{"kind":"externalParam","text":"presentationMode"},{"kind":"text","text":": "},{"text":"CallViewController","kind":"typeIdentifier","preciseIdentifier":"c:@M@KaleyraVideoSDK@objc(cs)CallViewController"},{"text":".","kind":"text"},{"preciseIdentifier":"s:15KaleyraVideoSDK18CallViewControllerC13ConfigurationV","text":"Configuration","kind":"typeIdentifier"},{"kind":"text","text":"."},{"kind":"typeIdentifier","preciseIdentifier":"s:15KaleyraVideoSDK18CallViewControllerC13ConfigurationV16PresentationModeO","text":"PresentationMode"},{"kind":"text","text":", "},{"kind":"externalParam","text":"animated"},{"text":": ","kind":"text"},{"text":"Bool","kind":"typeIdentifier","preciseIdentifier":"s:Sb"},{"kind":"text","text":", "},{"text":"completion","kind":"externalParam"},{"text":": (","kind":"text"},{"text":"Result","preciseIdentifier":"s:s6ResultO","kind":"typeIdentifier"},{"kind":"text","text":"<"},{"text":"Void","preciseIdentifier":"s:s4Voida","kind":"typeIdentifier"},{"kind":"text","text":", "},{"text":"Error","kind":"typeIdentifier","preciseIdentifier":"s:s5ErrorP"},{"text":">) -> ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"s:s4Voida","text":"Void"},{"text":")","kind":"text"}]},"doc://com.kaleyra.KaleyraVideoSDK/documentation/KaleyraVideoSDK/CallViewController/present(message:)":{"abstract":[{"type":"text","text":"Call this function when you want to present a "},{"type":"reference","isActive":true,"identifier":"doc:\/\/com.kaleyra.KaleyraVideoSDK\/documentation\/KaleyraVideoSDK\/FloatingMessage"},{"text":" object.","type":"text"}],"role":"symbol","title":"present(message:)","fragments":[{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"text":"present","kind":"identifier"},{"kind":"text","text":"("},{"kind":"externalParam","text":"message"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"s:15KaleyraVideoSDK15FloatingMessageC","text":"FloatingMessage"},{"text":")","kind":"text"}],"type":"topic","identifier":"doc:\/\/com.kaleyra.KaleyraVideoSDK\/documentation\/KaleyraVideoSDK\/CallViewController\/present(message:)","url":"\/documentation\/kaleyravideosdk\/callviewcontroller\/present(message:)","kind":"symbol"},"doc://com.kaleyra.KaleyraVideoSDK/SH":{"identifier":"doc:\/\/com.kaleyra.KaleyraVideoSDK\/SH","title":"Swift.Hashable","type":"unresolvable"},"doc://com.kaleyra.KaleyraVideoSDK/documentation/KaleyraVideoSDK/CallViewController/Configuration":{"kind":"symbol","navigatorTitle":[{"text":"Configuration","kind":"identifier"}],"title":"CallViewController.Configuration","abstract":[{"type":"text","text":"A value holding the UI customization for a "},{"type":"reference","identifier":"doc:\/\/com.kaleyra.KaleyraVideoSDK\/documentation\/KaleyraVideoSDK\/CallViewController","isActive":true},{"type":"text","text":" instance."}],"role":"symbol","fragments":[{"kind":"keyword","text":"struct"},{"kind":"text","text":" "},{"text":"Configuration","kind":"identifier"}],"identifier":"doc:\/\/com.kaleyra.KaleyraVideoSDK\/documentation\/KaleyraVideoSDK\/CallViewController\/Configuration","type":"topic","url":"\/documentation\/kaleyravideosdk\/callviewcontroller\/configuration"},"doc://com.kaleyra.KaleyraVideoSDK/documentation/KaleyraVideoSDK/CallViewController/init(call:configuration:)":{"identifier":"doc:\/\/com.kaleyra.KaleyraVideoSDK\/documentation\/KaleyraVideoSDK\/CallViewController\/init(call:configuration:)","abstract":[{"text":"Creates a new ","type":"text"},{"identifier":"doc:\/\/com.kaleyra.KaleyraVideoSDK\/documentation\/KaleyraVideoSDK\/CallViewController","isActive":true,"type":"reference"},{"text":" instance, bound to the ","type":"text"},{"type":"reference","isActive":true,"identifier":"doc:\/\/com.kaleyra.KaleyraVideoSDK\/documentation\/KaleyraVideoSDK\/Call"},{"type":"text","text":" object provided as argument."}],"kind":"symbol","title":"init(call:configuration:)","url":"\/documentation\/kaleyravideosdk\/callviewcontroller\/init(call:configuration:)","type":"topic","role":"symbol","fragments":[{"text":"init","kind":"identifier"},{"kind":"text","text":"("},{"text":"call","kind":"externalParam"},{"text":": KaleyraVideoSDK","kind":"text"},{"text":".","kind":"text"},{"preciseIdentifier":"s:15KaleyraVideoSDK4CallP","kind":"typeIdentifier","text":"Call"},{"text":", ","kind":"text"},{"text":"configuration","kind":"externalParam"},{"kind":"text","text":": "},{"preciseIdentifier":"c:@M@KaleyraVideoSDK@objc(cs)CallViewController","kind":"typeIdentifier","text":"CallViewController"},{"kind":"text","text":"."},{"kind":"typeIdentifier","preciseIdentifier":"s:15KaleyraVideoSDK18CallViewControllerC13ConfigurationV","text":"Configuration"},{"text":")","kind":"text"}]},"doc://com.kaleyra.KaleyraVideoSDK/objc(pl)UITraitEnvironment":{"type":"unresolvable","identifier":"doc:\/\/com.kaleyra.KaleyraVideoSDK\/objc(pl)UITraitEnvironment","title":"UIKit.UITraitEnvironment"},"doc://com.kaleyra.KaleyraVideoSDK/SQ":{"type":"unresolvable","identifier":"doc:\/\/com.kaleyra.KaleyraVideoSDK\/SQ","title":"Swift.Equatable"},"doc://com.kaleyra.KaleyraVideoSDK/documentation/KaleyraVideoSDK/CallViewController/viewDidDisappear:":{"kind":"symbol","navigatorTitle":[{"kind":"identifier","text":"viewDidDisappear:"}],"title":"viewDidDisappear:","abstract":[],"role":"symbol","fragments":[{"kind":"text","text":"- "},{"kind":"identifier","text":"viewDidDisappear:"}],"identifier":"doc:\/\/com.kaleyra.KaleyraVideoSDK\/documentation\/KaleyraVideoSDK\/CallViewController\/viewDidDisappear:","type":"topic","url":"\/documentation\/kaleyravideosdk\/callviewcontroller\/viewdiddisappear:"},"doc://com.kaleyra.KaleyraVideoSDK/documentation/KaleyraVideoSDK/CallViewController/viewDidLoad":{"identifier":"doc:\/\/com.kaleyra.KaleyraVideoSDK\/documentation\/KaleyraVideoSDK\/CallViewController\/viewDidLoad","abstract":[],"kind":"symbol","title":"viewDidLoad","navigatorTitle":[{"kind":"identifier","text":"viewDidLoad"}],"url":"\/documentation\/kaleyravideosdk\/callviewcontroller\/viewdidload","type":"topic","role":"symbol","fragments":[{"text":"- ","kind":"text"},{"kind":"identifier","text":"viewDidLoad"}]},"doc://com.kaleyra.KaleyraVideoSDK/objc(pl)UIStateRestoring":{"title":"UIKit.UIStateRestoring","identifier":"doc:\/\/com.kaleyra.KaleyraVideoSDK\/objc(pl)UIStateRestoring","type":"unresolvable"},"doc://com.kaleyra.KaleyraVideoSDK/objc(pl)UIResponderStandardEditActions":{"title":"UIKit.UIResponderStandardEditActions","identifier":"doc:\/\/com.kaleyra.KaleyraVideoSDK\/objc(pl)UIResponderStandardEditActions","type":"unresolvable"},"doc://com.kaleyra.KaleyraVideoSDK/documentation/KaleyraVideoSDK/CallViewController/dismiss(message:)":{"identifier":"doc:\/\/com.kaleyra.KaleyraVideoSDK\/documentation\/KaleyraVideoSDK\/CallViewController\/dismiss(message:)","abstract":[{"type":"text","text":"Call this function when you want to dismiss  a presented "},{"type":"reference","identifier":"doc:\/\/com.kaleyra.KaleyraVideoSDK\/documentation\/KaleyraVideoSDK\/FloatingMessage","isActive":true},{"type":"text","text":" object."}],"kind":"symbol","title":"dismiss(message:)","url":"\/documentation\/kaleyravideosdk\/callviewcontroller\/dismiss(message:)","type":"topic","role":"symbol","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"text":"dismiss","kind":"identifier"},{"text":"(","kind":"text"},{"kind":"externalParam","text":"message"},{"text":": ","kind":"text"},{"text":"FloatingMessage","kind":"typeIdentifier","preciseIdentifier":"s:15KaleyraVideoSDK15FloatingMessageC"},{"text":")","kind":"text"}]},"doc://com.kaleyra.KaleyraVideoSDK/objc(pl)NSCoding":{"identifier":"doc:\/\/com.kaleyra.KaleyraVideoSDK\/objc(pl)NSCoding","type":"unresolvable","title":"Foundation.NSCoding"},"doc://com.kaleyra.KaleyraVideoSDK/17KaleyraFoundation21PropertyProxyProviderP":{"identifier":"doc:\/\/com.kaleyra.KaleyraVideoSDK\/17KaleyraFoundation21PropertyProxyProviderP","type":"unresolvable","title":"KaleyraFoundation.PropertyProxyProvider"},"doc://com.kaleyra.KaleyraVideoSDK/5UIKit23UITraitChangeObservableP":{"identifier":"doc:\/\/com.kaleyra.KaleyraVideoSDK\/5UIKit23UITraitChangeObservableP","type":"unresolvable","title":"UIKit.UITraitChangeObservable"},"doc://com.kaleyra.KaleyraVideoSDK/objc(pl)UIActivityItemsConfigurationProviding":{"identifier":"doc:\/\/com.kaleyra.KaleyraVideoSDK\/objc(pl)UIActivityItemsConfigurationProviding","type":"unresolvable","title":"UIKit.UIActivityItemsConfigurationProviding"},"doc://com.kaleyra.KaleyraVideoSDK/s23CustomStringConvertibleP":{"identifier":"doc:\/\/com.kaleyra.KaleyraVideoSDK\/s23CustomStringConvertibleP","type":"unresolvable","title":"Swift.CustomStringConvertible"},"doc://com.kaleyra.KaleyraVideoSDK/objc(pl)UIAppearanceContainer":{"identifier":"doc:\/\/com.kaleyra.KaleyraVideoSDK\/objc(pl)UIAppearanceContainer","type":"unresolvable","title":"UIKit.UIAppearanceContainer"},"doc://com.kaleyra.KaleyraVideoSDK/objc(pl)UIContentContainer":{"identifier":"doc:\/\/com.kaleyra.KaleyraVideoSDK\/objc(pl)UIContentContainer","type":"unresolvable","title":"UIKit.UIContentContainer"},"doc://com.kaleyra.KaleyraVideoSDK/17KaleyraFoundation18SubscriptionsOwnerP":{"identifier":"doc:\/\/com.kaleyra.KaleyraVideoSDK\/17KaleyraFoundation18SubscriptionsOwnerP","type":"unresolvable","title":"KaleyraFoundation.SubscriptionsOwner"},"doc://com.kaleyra.KaleyraVideoSDK/objc(pl)NSObject":{"identifier":"doc:\/\/com.kaleyra.KaleyraVideoSDK\/objc(pl)NSObject","type":"unresolvable","title":"ObjectiveC.NSObjectProtocol"},"doc://com.kaleyra.KaleyraVideoSDK/documentation/KaleyraVideoSDK/CallViewController/delegate":{"abstract":[{"text":"The view controller’s delegate.","type":"text"}],"url":"\/documentation\/kaleyravideosdk\/callviewcontroller\/delegate","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"text":"delegate","kind":"identifier"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"CallViewControllerDelegate","preciseIdentifier":"s:15KaleyraVideoSDK26CallViewControllerDelegateP"},{"text":"?","kind":"text"}],"role":"symbol","title":"delegate","identifier":"doc:\/\/com.kaleyra.KaleyraVideoSDK\/documentation\/KaleyraVideoSDK\/CallViewController\/delegate","kind":"symbol","type":"topic"},"doc://com.kaleyra.KaleyraVideoSDK/objc(cs)UIViewController":{"identifier":"doc:\/\/com.kaleyra.KaleyraVideoSDK\/objc(cs)UIViewController","type":"unresolvable","title":"UIViewController"},"doc://com.kaleyra.KaleyraVideoSDK/objc(pl)UIPasteConfigurationSupporting":{"identifier":"doc:\/\/com.kaleyra.KaleyraVideoSDK\/objc(pl)UIPasteConfigurationSupporting","type":"unresolvable","title":"UIKit.UIPasteConfigurationSupporting"},"doc://com.kaleyra.KaleyraVideoSDK/documentation/KaleyraVideoSDK/CallViewController":{"title":"CallViewController","type":"topic","fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"text":"CallViewController","kind":"identifier"}],"role":"symbol","kind":"symbol","abstract":[{"type":"text","text":"A view controller showing a call user interface"}],"identifier":"doc:\/\/com.kaleyra.KaleyraVideoSDK\/documentation\/KaleyraVideoSDK\/CallViewController","url":"\/documentation\/kaleyravideosdk\/callviewcontroller","navigatorTitle":[{"kind":"identifier","text":"CallViewController"}]},"doc://com.kaleyra.KaleyraVideoSDK/documentation/KaleyraVideoSDK/FloatingMessage":{"kind":"symbol","url":"\/documentation\/kaleyravideosdk\/floatingmessage","navigatorTitle":[{"kind":"identifier","text":"FloatingMessage"}],"abstract":[{"type":"text","text":"The model object used for presenting floating messages during a call."}],"type":"topic","identifier":"doc:\/\/com.kaleyra.KaleyraVideoSDK\/documentation\/KaleyraVideoSDK\/FloatingMessage","title":"FloatingMessage","role":"symbol","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"text":"FloatingMessage","kind":"identifier"}]},"doc://com.kaleyra.KaleyraVideoSDK/objc(pl)NSExtensionRequestHandling":{"type":"unresolvable","title":"Foundation.NSExtensionRequestHandling","identifier":"doc:\/\/com.kaleyra.KaleyraVideoSDK\/objc(pl)NSExtensionRequestHandling"},"doc://com.kaleyra.KaleyraVideoSDK/objc(pl)UIUserActivityRestoring":{"type":"unresolvable","title":"UIKit.UIUserActivityRestoring","identifier":"doc:\/\/com.kaleyra.KaleyraVideoSDK\/objc(pl)UIUserActivityRestoring"},"doc://com.kaleyra.KaleyraVideoSDK/s7CVarArgP":{"title":"Swift.CVarArg","type":"unresolvable","identifier":"doc:\/\/com.kaleyra.KaleyraVideoSDK\/s7CVarArgP"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"value":"occ","op":"replace","path":"\/identifier\/interfaceLanguage"},{"value":[{"introducedAt":"15.0","deprecated":false,"unavailable":false,"beta":false,"name":"iOS"}],"path":"\/metadata\/platforms","op":"replace"},{"value":"Class","path":"\/metadata\/roleHeading","op":"replace"},{"path":"\/metadata\/title","value":"CallViewController","op":"replace"},{"op":"replace","path":"\/metadata\/symbolKind","value":"class"},{"path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"CallViewController"}],"op":"replace"},{"value":[{"text":"CallViewController","kind":"identifier"}],"path":"\/metadata\/navigatorTitle","op":"replace"},{"value":[{"identifiers":["doc:\/\/com.kaleyra.KaleyraVideoSDK\/documentation\/KaleyraVideoSDK\/CallViewController\/loadView","doc:\/\/com.kaleyra.KaleyraVideoSDK\/documentation\/KaleyraVideoSDK\/CallViewController\/viewDidDisappear:","doc:\/\/com.kaleyra.KaleyraVideoSDK\/documentation\/KaleyraVideoSDK\/CallViewController\/viewDidLoad","doc:\/\/com.kaleyra.KaleyraVideoSDK\/documentation\/KaleyraVideoSDK\/CallViewController\/viewWillAppear:"],"title":"Instance Methods"}],"path":"\/topicSections","op":"replace"},{"op":"replace","path":"\/relationshipsSections","value":[{"kind":"relationships","type":"inheritsFrom","identifiers":["doc:\/\/com.kaleyra.KaleyraVideoSDK\/objc(cs)UIViewController"],"title":"Inherits From"}]},{"value":null,"op":"add","path":"\/seeAlsoSections"},{"value":{"declarations":[{"languages":["occ"],"tokens":[{"kind":"keyword","text":"@interface"},{"kind":"text","text":" "},{"text":"CallViewController","kind":"identifier"},{"kind":"text","text":" : "},{"text":"UIViewController","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)UIViewController"}],"platforms":["iOS"]}],"kind":"declarations"},"path":"\/primaryContentSections\/0","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1com.kaleyra.KaleyraVideoSDK~1documentation~1KaleyraVideoSDK~1CallWindow\/title","value":"CallWindow"},{"op":"replace","path":"\/references\/doc:~1~1com.kaleyra.KaleyraVideoSDK~1documentation~1KaleyraVideoSDK~1CallWindow\/fragments","value":[{"text":"CallWindow","kind":"identifier"}]},{"path":"\/references\/doc:~1~1com.kaleyra.KaleyraVideoSDK~1documentation~1KaleyraVideoSDK~1CallViewController\/title","op":"replace","value":"CallViewController"},{"path":"\/references\/doc:~1~1com.kaleyra.KaleyraVideoSDK~1documentation~1KaleyraVideoSDK~1CallViewController\/fragments","value":[{"kind":"identifier","text":"CallViewController"}],"op":"replace"}]}]}