{"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/kaleyravideosdk\/channelviewcontroller"]},{"paths":["\/documentation\/kaleyravideosdk\/channelviewcontroller"],"traits":[{"interfaceLanguage":"occ"}]}],"relationshipsSections":[{"kind":"relationships","type":"inheritsFrom","identifiers":["doc:\/\/com.kaleyra.KaleyraVideoSDK\/objc(cs)UIViewController"],"title":"Inherits From"},{"title":"Conforms To","identifiers":["doc:\/\/com.kaleyra.KaleyraVideoSDK\/objc(pl)NSCoding","doc:\/\/com.kaleyra.KaleyraVideoSDK\/objc(pl)NSExtensionRequestHandling","doc:\/\/com.kaleyra.KaleyraVideoSDK\/objc(pl)NSObject","doc:\/\/com.kaleyra.KaleyraVideoSDK\/s7CVarArgP","doc:\/\/com.kaleyra.KaleyraVideoSDK\/s28CustomDebugStringConvertibleP","doc:\/\/com.kaleyra.KaleyraVideoSDK\/s23CustomStringConvertibleP","doc:\/\/com.kaleyra.KaleyraVideoSDK\/SQ","doc:\/\/com.kaleyra.KaleyraVideoSDK\/SH","doc:\/\/com.kaleyra.KaleyraVideoSDK\/s8SendableP","doc:\/\/com.kaleyra.KaleyraVideoSDK\/objc(pl)UIActivityItemsConfigurationProviding","doc:\/\/com.kaleyra.KaleyraVideoSDK\/objc(pl)UIAppearanceContainer","doc:\/\/com.kaleyra.KaleyraVideoSDK\/objc(pl)UIBarPositioningDelegate","doc:\/\/com.kaleyra.KaleyraVideoSDK\/objc(pl)UIContentContainer","doc:\/\/com.kaleyra.KaleyraVideoSDK\/objc(pl)UIFocusEnvironment","doc:\/\/com.kaleyra.KaleyraVideoSDK\/objc(pl)UINavigationBarDelegate","doc:\/\/com.kaleyra.KaleyraVideoSDK\/objc(pl)UIPasteConfigurationSupporting","doc:\/\/com.kaleyra.KaleyraVideoSDK\/objc(pl)UIResponderStandardEditActions","doc:\/\/com.kaleyra.KaleyraVideoSDK\/objc(pl)UIStateRestoring","doc:\/\/com.kaleyra.KaleyraVideoSDK\/5UIKit23UITraitChangeObservableP","doc:\/\/com.kaleyra.KaleyraVideoSDK\/objc(pl)UITraitEnvironment","doc:\/\/com.kaleyra.KaleyraVideoSDK\/objc(pl)UIUserActivityRestoring"],"kind":"relationships","type":"conformsTo"}],"topicSections":[{"identifiers":["doc:\/\/com.kaleyra.KaleyraVideoSDK\/documentation\/KaleyraVideoSDK\/ChannelViewController\/Configuration-swift.struct"],"title":"Structures"},{"title":"Initializers","identifiers":["doc:\/\/com.kaleyra.KaleyraVideoSDK\/documentation\/KaleyraVideoSDK\/ChannelViewController\/init(intent:configuration:)"]},{"title":"Instance Properties","identifiers":["doc:\/\/com.kaleyra.KaleyraVideoSDK\/documentation\/KaleyraVideoSDK\/ChannelViewController\/configuration-swift.property","doc:\/\/com.kaleyra.KaleyraVideoSDK\/documentation\/KaleyraVideoSDK\/ChannelViewController\/delegate"]},{"title":"Enumerations","identifiers":["doc:\/\/com.kaleyra.KaleyraVideoSDK\/documentation\/KaleyraVideoSDK\/ChannelViewController\/Intent"]},{"identifiers":["doc:\/\/com.kaleyra.KaleyraVideoSDK\/documentation\/KaleyraVideoSDK\/ChannelViewController\/UIBarPositioningDelegate-Implementations"],"title":"Default Implementations","generated":true}],"hierarchy":{"paths":[["doc:\/\/com.kaleyra.KaleyraVideoSDK\/documentation\/KaleyraVideoSDK"]]},"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/com.kaleyra.KaleyraVideoSDK\/documentation\/KaleyraVideoSDK\/ChannelViewController"},"kind":"symbol","sections":[],"metadata":{"modules":[{"name":"KaleyraVideoSDK"}],"role":"symbol","externalID":"c:@M@KaleyraVideoSDK@objc(cs)ChannelViewController","symbolKind":"class","title":"ChannelViewController","fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"text":"ChannelViewController","kind":"identifier"}],"roleHeading":"Class","navigatorTitle":[{"text":"ChannelViewController","kind":"identifier"}]},"schemaVersion":{"major":0,"patch":0,"minor":3},"abstract":[{"type":"text","text":"A view controller showing the user interface of a chat"}],"primaryContentSections":[{"kind":"declarations","declarations":[{"platforms":["iOS"],"tokens":[{"text":"final","kind":"keyword"},{"text":" ","kind":"text"},{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"ChannelViewController","kind":"identifier"}],"languages":["swift"]}]},{"kind":"content","content":[{"text":"Overview","type":"heading","anchor":"overview","level":2},{"type":"paragraph","inlineContent":[{"type":"text","text":"This view controller should be presented modally. You should not embed this view controller in a "},{"type":"codeVoice","code":"UINavigationController"}]}]}],"references":{"doc://com.kaleyra.KaleyraVideoSDK/s23CustomStringConvertibleP":{"title":"Swift.CustomStringConvertible","type":"unresolvable","identifier":"doc:\/\/com.kaleyra.KaleyraVideoSDK\/s23CustomStringConvertibleP"},"doc://com.kaleyra.KaleyraVideoSDK/objc(pl)NSExtensionRequestHandling":{"type":"unresolvable","identifier":"doc:\/\/com.kaleyra.KaleyraVideoSDK\/objc(pl)NSExtensionRequestHandling","title":"Foundation.NSExtensionRequestHandling"},"doc://com.kaleyra.KaleyraVideoSDK/SQ":{"title":"Swift.Equatable","type":"unresolvable","identifier":"doc:\/\/com.kaleyra.KaleyraVideoSDK\/SQ"},"doc://com.kaleyra.KaleyraVideoSDK/documentation/KaleyraVideoSDK/ChannelViewController/Configuration-swift.struct":{"kind":"symbol","navigatorTitle":[{"kind":"identifier","text":"Configuration"}],"identifier":"doc:\/\/com.kaleyra.KaleyraVideoSDK\/documentation\/KaleyraVideoSDK\/ChannelViewController\/Configuration-swift.struct","type":"topic","title":"ChannelViewController.Configuration","fragments":[{"text":"struct","kind":"keyword"},{"text":" ","kind":"text"},{"text":"Configuration","kind":"identifier"}],"url":"\/documentation\/kaleyravideosdk\/channelviewcontroller\/configuration-swift.struct","abstract":[{"type":"text","text":"A value holding the customization available for a "},{"identifier":"doc:\/\/com.kaleyra.KaleyraVideoSDK\/documentation\/KaleyraVideoSDK\/ChannelViewController","type":"reference","isActive":true},{"type":"text","text":" instance."}],"role":"symbol"},"doc://com.kaleyra.KaleyraVideoSDK/documentation/KaleyraVideoSDK/ChannelViewController":{"identifier":"doc:\/\/com.kaleyra.KaleyraVideoSDK\/documentation\/KaleyraVideoSDK\/ChannelViewController","url":"\/documentation\/kaleyravideosdk\/channelviewcontroller","type":"topic","abstract":[{"type":"text","text":"A view controller showing the user interface of a chat"}],"fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"text":"ChannelViewController","kind":"identifier"}],"navigatorTitle":[{"text":"ChannelViewController","kind":"identifier"}],"title":"ChannelViewController","kind":"symbol","role":"symbol"},"doc://com.kaleyra.KaleyraVideoSDK/documentation/KaleyraVideoSDK/ChannelViewController/viewDidLoad":{"navigatorTitle":[{"kind":"identifier","text":"viewDidLoad"}],"url":"\/documentation\/kaleyravideosdk\/channelviewcontroller\/viewdidload","title":"viewDidLoad","type":"topic","kind":"symbol","role":"symbol","fragments":[{"kind":"text","text":"- "},{"kind":"identifier","text":"viewDidLoad"}],"identifier":"doc:\/\/com.kaleyra.KaleyraVideoSDK\/documentation\/KaleyraVideoSDK\/ChannelViewController\/viewDidLoad","abstract":[]},"doc://com.kaleyra.KaleyraVideoSDK/documentation/KaleyraVideoSDK/ChannelViewController/delegate":{"fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"text":"delegate","kind":"identifier"},{"text":": ","kind":"text"},{"text":"ChannelViewControllerDelegate","preciseIdentifier":"s:15KaleyraVideoSDK29ChannelViewControllerDelegateP","kind":"typeIdentifier"},{"kind":"text","text":"?"}],"identifier":"doc:\/\/com.kaleyra.KaleyraVideoSDK\/documentation\/KaleyraVideoSDK\/ChannelViewController\/delegate","type":"topic","title":"delegate","abstract":[{"text":"The view controller’s delegate.","type":"text"}],"role":"symbol","url":"\/documentation\/kaleyravideosdk\/channelviewcontroller\/delegate","kind":"symbol"},"doc://com.kaleyra.KaleyraVideoSDK/s28CustomDebugStringConvertibleP":{"title":"Swift.CustomDebugStringConvertible","type":"unresolvable","identifier":"doc:\/\/com.kaleyra.KaleyraVideoSDK\/s28CustomDebugStringConvertibleP"},"doc://com.kaleyra.KaleyraVideoSDK/documentation/KaleyraVideoSDK/ChannelViewController/configuration-swift.property":{"kind":"symbol","title":"configuration","abstract":[{"type":"text","text":"The "},{"type":"reference","identifier":"doc:\/\/com.kaleyra.KaleyraVideoSDK\/documentation\/KaleyraVideoSDK\/ChannelViewController\/Configuration-swift.struct","isActive":true},{"type":"text","text":" used to configure this view controller."}],"fragments":[{"kind":"keyword","text":"let"},{"kind":"text","text":" "},{"kind":"identifier","text":"configuration"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@KaleyraVideoSDK@objc(cs)ChannelViewController","text":"ChannelViewController"},{"kind":"text","text":"."},{"kind":"typeIdentifier","text":"Configuration","preciseIdentifier":"s:15KaleyraVideoSDK21ChannelViewControllerC13ConfigurationV"}],"url":"\/documentation\/kaleyravideosdk\/channelviewcontroller\/configuration-swift.property","role":"symbol","identifier":"doc:\/\/com.kaleyra.KaleyraVideoSDK\/documentation\/KaleyraVideoSDK\/ChannelViewController\/configuration-swift.property","type":"topic"},"doc://com.kaleyra.KaleyraVideoSDK/objc(pl)NSObject":{"title":"ObjectiveC.NSObjectProtocol","type":"unresolvable","identifier":"doc:\/\/com.kaleyra.KaleyraVideoSDK\/objc(pl)NSObject"},"doc://com.kaleyra.KaleyraVideoSDK/objc(pl)NSCoding":{"title":"Foundation.NSCoding","type":"unresolvable","identifier":"doc:\/\/com.kaleyra.KaleyraVideoSDK\/objc(pl)NSCoding"},"doc://com.kaleyra.KaleyraVideoSDK/documentation/KaleyraVideoSDK/ChannelViewController/Intent":{"abstract":[{"text":"A value representing the channel you want to be shown by the view controller.","type":"text"}],"type":"topic","role":"symbol","fragments":[{"text":"enum","kind":"keyword"},{"kind":"text","text":" "},{"text":"Intent","kind":"identifier"}],"navigatorTitle":[{"text":"Intent","kind":"identifier"}],"title":"ChannelViewController.Intent","identifier":"doc:\/\/com.kaleyra.KaleyraVideoSDK\/documentation\/KaleyraVideoSDK\/ChannelViewController\/Intent","kind":"symbol","url":"\/documentation\/kaleyravideosdk\/channelviewcontroller\/intent"},"doc://com.kaleyra.KaleyraVideoSDK/SH":{"title":"Swift.Hashable","type":"unresolvable","identifier":"doc:\/\/com.kaleyra.KaleyraVideoSDK\/SH"},"doc://com.kaleyra.KaleyraVideoSDK/objc(pl)UIUserActivityRestoring":{"title":"UIKit.UIUserActivityRestoring","type":"unresolvable","identifier":"doc:\/\/com.kaleyra.KaleyraVideoSDK\/objc(pl)UIUserActivityRestoring"},"doc://com.kaleyra.KaleyraVideoSDK/objc(pl)UIAppearanceContainer":{"type":"unresolvable","identifier":"doc:\/\/com.kaleyra.KaleyraVideoSDK\/objc(pl)UIAppearanceContainer","title":"UIKit.UIAppearanceContainer"},"doc://com.kaleyra.KaleyraVideoSDK/objc(pl)UIStateRestoring":{"title":"UIKit.UIStateRestoring","type":"unresolvable","identifier":"doc:\/\/com.kaleyra.KaleyraVideoSDK\/objc(pl)UIStateRestoring"},"doc://com.kaleyra.KaleyraVideoSDK/objc(cs)UIViewController":{"title":"UIViewController","type":"unresolvable","identifier":"doc:\/\/com.kaleyra.KaleyraVideoSDK\/objc(cs)UIViewController"},"doc://com.kaleyra.KaleyraVideoSDK/documentation/KaleyraVideoSDK":{"url":"\/documentation\/kaleyravideosdk","identifier":"doc:\/\/com.kaleyra.KaleyraVideoSDK\/documentation\/KaleyraVideoSDK","title":"KaleyraVideoSDK","kind":"symbol","role":"collection","type":"topic","abstract":[]},"doc://com.kaleyra.KaleyraVideoSDK/objc(pl)UIContentContainer":{"title":"UIKit.UIContentContainer","type":"unresolvable","identifier":"doc:\/\/com.kaleyra.KaleyraVideoSDK\/objc(pl)UIContentContainer"},"doc://com.kaleyra.KaleyraVideoSDK/objc(pl)UIActivityItemsConfigurationProviding":{"title":"UIKit.UIActivityItemsConfigurationProviding","type":"unresolvable","identifier":"doc:\/\/com.kaleyra.KaleyraVideoSDK\/objc(pl)UIActivityItemsConfigurationProviding"},"doc://com.kaleyra.KaleyraVideoSDK/objc(pl)UIBarPositioningDelegate":{"title":"UIKit.UIBarPositioningDelegate","type":"unresolvable","identifier":"doc:\/\/com.kaleyra.KaleyraVideoSDK\/objc(pl)UIBarPositioningDelegate"},"doc://com.kaleyra.KaleyraVideoSDK/objc(pl)UINavigationBarDelegate":{"type":"unresolvable","identifier":"doc:\/\/com.kaleyra.KaleyraVideoSDK\/objc(pl)UINavigationBarDelegate","title":"UINavigationBarDelegate"},"doc://com.kaleyra.KaleyraVideoSDK/documentation/KaleyraVideoSDK/ChannelViewController/init(intent:configuration:)":{"kind":"symbol","identifier":"doc:\/\/com.kaleyra.KaleyraVideoSDK\/documentation\/KaleyraVideoSDK\/ChannelViewController\/init(intent:configuration:)","type":"topic","title":"init(intent:configuration:)","fragments":[{"text":"init","kind":"identifier"},{"kind":"text","text":"("},{"text":"intent","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"Intent","preciseIdentifier":"s:15KaleyraVideoSDK21ChannelViewControllerC6IntentO","kind":"typeIdentifier"},{"kind":"text","text":", "},{"text":"configuration","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:@M@KaleyraVideoSDK@objc(cs)ChannelViewController","text":"ChannelViewController","kind":"typeIdentifier"},{"text":".","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"s:15KaleyraVideoSDK21ChannelViewControllerC13ConfigurationV","text":"Configuration"},{"text":")","kind":"text"}],"abstract":[{"type":"text","text":"Creates an instance bound to the Chat represented by the intent provided in initialisation"}],"url":"\/documentation\/kaleyravideosdk\/channelviewcontroller\/init(intent:configuration:)","role":"symbol"},"doc://com.kaleyra.KaleyraVideoSDK/objc(pl)UIResponderStandardEditActions":{"title":"UIKit.UIResponderStandardEditActions","type":"unresolvable","identifier":"doc:\/\/com.kaleyra.KaleyraVideoSDK\/objc(pl)UIResponderStandardEditActions"},"doc://com.kaleyra.KaleyraVideoSDK/documentation/KaleyraVideoSDK/ChannelViewController/canBecomeFirstResponder":{"abstract":[],"title":"canBecomeFirstResponder","role":"symbol","fragments":[{"text":"canBecomeFirstResponder","kind":"identifier"}],"kind":"symbol","identifier":"doc:\/\/com.kaleyra.KaleyraVideoSDK\/documentation\/KaleyraVideoSDK\/ChannelViewController\/canBecomeFirstResponder","url":"\/documentation\/kaleyravideosdk\/channelviewcontroller\/canbecomefirstresponder","type":"topic"},"doc://com.kaleyra.KaleyraVideoSDK/documentation/KaleyraVideoSDK/ChannelViewController/viewDidLayoutSubviews":{"abstract":[],"kind":"symbol","navigatorTitle":[{"text":"viewDidLayoutSubviews","kind":"identifier"}],"role":"symbol","identifier":"doc:\/\/com.kaleyra.KaleyraVideoSDK\/documentation\/KaleyraVideoSDK\/ChannelViewController\/viewDidLayoutSubviews","type":"topic","url":"\/documentation\/kaleyravideosdk\/channelviewcontroller\/viewdidlayoutsubviews","fragments":[{"text":"- ","kind":"text"},{"kind":"identifier","text":"viewDidLayoutSubviews"}],"title":"viewDidLayoutSubviews"},"doc://com.kaleyra.KaleyraVideoSDK/s7CVarArgP":{"type":"unresolvable","identifier":"doc:\/\/com.kaleyra.KaleyraVideoSDK\/s7CVarArgP","title":"Swift.CVarArg"},"doc://com.kaleyra.KaleyraVideoSDK/objc(pl)UIFocusEnvironment":{"type":"unresolvable","identifier":"doc:\/\/com.kaleyra.KaleyraVideoSDK\/objc(pl)UIFocusEnvironment","title":"UIKit.UIFocusEnvironment"},"doc://com.kaleyra.KaleyraVideoSDK/objc(pl)UITraitEnvironment":{"type":"unresolvable","identifier":"doc:\/\/com.kaleyra.KaleyraVideoSDK\/objc(pl)UITraitEnvironment","title":"UIKit.UITraitEnvironment"},"doc://com.kaleyra.KaleyraVideoSDK/objc(pl)UIPasteConfigurationSupporting":{"type":"unresolvable","identifier":"doc:\/\/com.kaleyra.KaleyraVideoSDK\/objc(pl)UIPasteConfigurationSupporting","title":"UIKit.UIPasteConfigurationSupporting"},"doc://com.kaleyra.KaleyraVideoSDK/documentation/KaleyraVideoSDK/ChannelViewController/UIBarPositioningDelegate-Implementations":{"role":"collectionGroup","identifier":"doc:\/\/com.kaleyra.KaleyraVideoSDK\/documentation\/KaleyraVideoSDK\/ChannelViewController\/UIBarPositioningDelegate-Implementations","url":"\/documentation\/kaleyravideosdk\/channelviewcontroller\/uibarpositioningdelegate-implementations","title":"UIBarPositioningDelegate Implementations","type":"topic","kind":"article","abstract":[]},"doc://com.kaleyra.KaleyraVideoSDK/s8SendableP":{"title":"Swift.Sendable","type":"unresolvable","identifier":"doc:\/\/com.kaleyra.KaleyraVideoSDK\/s8SendableP"},"doc://com.kaleyra.KaleyraVideoSDK/5UIKit23UITraitChangeObservableP":{"title":"UIKit.UITraitChangeObservable","type":"unresolvable","identifier":"doc:\/\/com.kaleyra.KaleyraVideoSDK\/5UIKit23UITraitChangeObservableP"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"path":"\/metadata\/roleHeading","op":"replace","value":"Class"},{"path":"\/metadata\/title","value":"ChannelViewController","op":"replace"},{"op":"replace","value":"class","path":"\/metadata\/symbolKind"},{"path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"ChannelViewController"}],"op":"replace"},{"value":[{"text":"ChannelViewController","kind":"identifier"}],"op":"replace","path":"\/metadata\/navigatorTitle"},{"op":"replace","path":"\/topicSections","value":[{"identifiers":["doc:\/\/com.kaleyra.KaleyraVideoSDK\/documentation\/KaleyraVideoSDK\/ChannelViewController\/canBecomeFirstResponder"],"title":"Instance Properties"},{"identifiers":["doc:\/\/com.kaleyra.KaleyraVideoSDK\/documentation\/KaleyraVideoSDK\/ChannelViewController\/viewDidLayoutSubviews","doc:\/\/com.kaleyra.KaleyraVideoSDK\/documentation\/KaleyraVideoSDK\/ChannelViewController\/viewDidLoad"],"title":"Instance Methods"},{"title":"Default Implementations","identifiers":["doc:\/\/com.kaleyra.KaleyraVideoSDK\/documentation\/KaleyraVideoSDK\/ChannelViewController\/UIBarPositioningDelegate-Implementations"],"generated":true}]},{"path":"\/relationshipsSections","value":[{"kind":"relationships","type":"inheritsFrom","title":"Inherits From","identifiers":["doc:\/\/com.kaleyra.KaleyraVideoSDK\/objc(cs)UIViewController"]},{"kind":"relationships","type":"conformsTo","title":"Conforms To","identifiers":["doc:\/\/com.kaleyra.KaleyraVideoSDK\/objc(pl)UINavigationBarDelegate"]}],"op":"replace"},{"value":null,"path":"\/seeAlsoSections","op":"add"},{"op":"replace","value":{"declarations":[{"languages":["occ"],"platforms":["iOS"],"tokens":[{"kind":"keyword","text":"@interface"},{"text":" ","kind":"text"},{"text":"ChannelViewController","kind":"identifier"},{"text":" : ","kind":"text"},{"preciseIdentifier":"c:objc(cs)UIViewController","text":"UIViewController","kind":"typeIdentifier"}]}],"kind":"declarations"},"path":"\/primaryContentSections\/0"},{"op":"replace","path":"\/references\/doc:~1~1com.kaleyra.KaleyraVideoSDK~1documentation~1KaleyraVideoSDK~1ChannelViewController\/title","value":"ChannelViewController"},{"value":[{"kind":"identifier","text":"ChannelViewController"}],"path":"\/references\/doc:~1~1com.kaleyra.KaleyraVideoSDK~1documentation~1KaleyraVideoSDK~1ChannelViewController\/fragments","op":"replace"}],"traits":[{"interfaceLanguage":"occ"}]}]}