{"variants":[{"paths":["\/documentation\/kaleyravideosdk"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/kaleyravideosdk"],"traits":[{"interfaceLanguage":"occ"}]}],"hierarchy":{"paths":[[]]},"topicSections":[{"title":"Classes","identifiers":["doc:\/\/com.kaleyra.KaleyraVideoSDK\/documentation\/KaleyraVideoSDK\/CallRecording","doc:\/\/com.kaleyra.KaleyraVideoSDK\/documentation\/KaleyraVideoSDK\/CallViewController","doc:\/\/com.kaleyra.KaleyraVideoSDK\/documentation\/KaleyraVideoSDK\/CallWindow","doc:\/\/com.kaleyra.KaleyraVideoSDK\/documentation\/KaleyraVideoSDK\/ChatViewController","doc:\/\/com.kaleyra.KaleyraVideoSDK\/documentation\/KaleyraVideoSDK\/KaleyraVideo"]},{"identifiers":["doc:\/\/com.kaleyra.KaleyraVideoSDK\/documentation\/KaleyraVideoSDK\/AccessTokenProvider","doc:\/\/com.kaleyra.KaleyraVideoSDK\/documentation\/KaleyraVideoSDK\/Call","doc:\/\/com.kaleyra.KaleyraVideoSDK\/documentation\/KaleyraVideoSDK\/CallParticipant","doc:\/\/com.kaleyra.KaleyraVideoSDK\/documentation\/KaleyraVideoSDK\/CallParticipants","doc:\/\/com.kaleyra.KaleyraVideoSDK\/documentation\/KaleyraVideoSDK\/CallViewControllerDelegate","doc:\/\/com.kaleyra.KaleyraVideoSDK\/documentation\/KaleyraVideoSDK\/ChatViewControllerDelegate","doc:\/\/com.kaleyra.KaleyraVideoSDK\/documentation\/KaleyraVideoSDK\/Conference","doc:\/\/com.kaleyra.KaleyraVideoSDK\/documentation\/KaleyraVideoSDK\/Conversation","doc:\/\/com.kaleyra.KaleyraVideoSDK\/documentation\/KaleyraVideoSDK\/InAppNotifications","doc:\/\/com.kaleyra.KaleyraVideoSDK\/documentation\/KaleyraVideoSDK\/InAppNotificationsDelegate","doc:\/\/com.kaleyra.KaleyraVideoSDK\/documentation\/KaleyraVideoSDK\/UserDetailsProvider"],"title":"Protocols"},{"title":"Structures","identifiers":["doc:\/\/com.kaleyra.KaleyraVideoSDK\/documentation\/KaleyraVideoSDK\/AppGroupIdentifier","doc:\/\/com.kaleyra.KaleyraVideoSDK\/documentation\/KaleyraVideoSDK\/CallOptions","doc:\/\/com.kaleyra.KaleyraVideoSDK\/documentation\/KaleyraVideoSDK\/ChatNotification","doc:\/\/com.kaleyra.KaleyraVideoSDK\/documentation\/KaleyraVideoSDK\/ConferenceSettings","doc:\/\/com.kaleyra.KaleyraVideoSDK\/documentation\/KaleyraVideoSDK\/Config","doc:\/\/com.kaleyra.KaleyraVideoSDK\/documentation\/KaleyraVideoSDK\/Environment","doc:\/\/com.kaleyra.KaleyraVideoSDK\/documentation\/KaleyraVideoSDK\/Loggers","doc:\/\/com.kaleyra.KaleyraVideoSDK\/documentation\/KaleyraVideoSDK\/Region","doc:\/\/com.kaleyra.KaleyraVideoSDK\/documentation\/KaleyraVideoSDK\/Theme","doc:\/\/com.kaleyra.KaleyraVideoSDK\/documentation\/KaleyraVideoSDK\/UserDetails","doc:\/\/com.kaleyra.KaleyraVideoSDK\/documentation\/KaleyraVideoSDK\/VoIPCredentials"]},{"title":"Enumerations","identifiers":["doc:\/\/com.kaleyra.KaleyraVideoSDK\/documentation\/KaleyraVideoSDK\/CallParticipantState","doc:\/\/com.kaleyra.KaleyraVideoSDK\/documentation\/KaleyraVideoSDK\/CallState","doc:\/\/com.kaleyra.KaleyraVideoSDK\/documentation\/KaleyraVideoSDK\/ClientState","doc:\/\/com.kaleyra.KaleyraVideoSDK\/documentation\/KaleyraVideoSDK\/LogFlag","doc:\/\/com.kaleyra.KaleyraVideoSDK\/documentation\/KaleyraVideoSDK\/LogLevel"]}],"sections":[],"schemaVersion":{"minor":3,"major":0,"patch":0},"kind":"symbol","metadata":{"roleHeading":"Framework","externalID":"KaleyraVideoSDK","title":"KaleyraVideoSDK","role":"collection","modules":[{"name":"KaleyraVideoSDK"}],"symbolKind":"module"},"identifier":{"url":"doc:\/\/com.kaleyra.KaleyraVideoSDK\/documentation\/KaleyraVideoSDK","interfaceLanguage":"swift"},"references":{"doc://com.kaleyra.KaleyraVideoSDK/documentation/KaleyraVideoSDK/Conference":{"navigatorTitle":[{"text":"Conference","kind":"identifier"}],"role":"symbol","identifier":"doc:\/\/com.kaleyra.KaleyraVideoSDK\/documentation\/KaleyraVideoSDK\/Conference","url":"\/documentation\/kaleyravideosdk\/conference","fragments":[{"kind":"keyword","text":"protocol"},{"text":" ","kind":"text"},{"kind":"identifier","text":"Conference"}],"type":"topic","abstract":[{"type":"text","text":"An object representing the conference interface of the SDK."}],"kind":"symbol","title":"Conference"},"doc://com.kaleyra.KaleyraVideoSDK/documentation/KaleyraVideoSDK/AccessTokenProvider":{"type":"topic","abstract":[{"type":"text","text":"A component providing “access tokens” for a user."}],"kind":"symbol","title":"AccessTokenProvider","url":"\/documentation\/kaleyravideosdk\/accesstokenprovider","role":"symbol","identifier":"doc:\/\/com.kaleyra.KaleyraVideoSDK\/documentation\/KaleyraVideoSDK\/AccessTokenProvider","fragments":[{"text":"protocol","kind":"keyword"},{"text":" ","kind":"text"},{"text":"AccessTokenProvider","kind":"identifier"}],"navigatorTitle":[{"text":"AccessTokenProvider","kind":"identifier"}]},"doc://com.kaleyra.KaleyraVideoSDK/documentation/KaleyraVideoSDK/CallOptions":{"type":"topic","kind":"symbol","url":"\/documentation\/kaleyravideosdk\/calloptions","identifier":"doc:\/\/com.kaleyra.KaleyraVideoSDK\/documentation\/KaleyraVideoSDK\/CallOptions","role":"symbol","fragments":[{"text":"struct","kind":"keyword"},{"text":" ","kind":"text"},{"text":"CallOptions","kind":"identifier"}],"navigatorTitle":[{"text":"CallOptions","kind":"identifier"}],"abstract":[{"type":"text","text":"A value object representing the options used when creating a call."}],"title":"CallOptions"},"doc://com.kaleyra.KaleyraVideoSDK/documentation/KaleyraVideoSDK/Conversation":{"kind":"symbol","navigatorTitle":[{"kind":"identifier","text":"Conversation"}],"abstract":[{"text":"An object representing the Conversation service","type":"text"}],"title":"Conversation","url":"\/documentation\/kaleyravideosdk\/conversation","type":"topic","identifier":"doc:\/\/com.kaleyra.KaleyraVideoSDK\/documentation\/KaleyraVideoSDK\/Conversation","role":"symbol","fragments":[{"text":"protocol","kind":"keyword"},{"kind":"text","text":" "},{"text":"Conversation","kind":"identifier"}]},"doc://com.kaleyra.KaleyraVideoSDK/documentation/KaleyraVideoSDK/CallParticipants":{"kind":"symbol","type":"topic","identifier":"doc:\/\/com.kaleyra.KaleyraVideoSDK\/documentation\/KaleyraVideoSDK\/CallParticipants","url":"\/documentation\/kaleyravideosdk\/callparticipants","role":"symbol","fragments":[{"text":"protocol","kind":"keyword"},{"text":" ","kind":"text"},{"text":"CallParticipants","kind":"identifier"}],"navigatorTitle":[{"kind":"identifier","text":"CallParticipants"}],"abstract":[{"type":"text","text":"An object representing the participants inside a call and their state."}],"title":"CallParticipants"},"doc://com.kaleyra.KaleyraVideoSDK/documentation/KaleyraVideoSDK/Loggers":{"type":"topic","navigatorTitle":[{"kind":"identifier","text":"Loggers"}],"abstract":[{"text":"Options describing supported log outputs","type":"text"}],"kind":"symbol","identifier":"doc:\/\/com.kaleyra.KaleyraVideoSDK\/documentation\/KaleyraVideoSDK\/Loggers","title":"Loggers","url":"\/documentation\/kaleyravideosdk\/loggers","role":"symbol","fragments":[{"text":"struct","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"Loggers"}]},"doc://com.kaleyra.KaleyraVideoSDK/documentation/KaleyraVideoSDK/UserDetailsProvider":{"identifier":"doc:\/\/com.kaleyra.KaleyraVideoSDK\/documentation\/KaleyraVideoSDK\/UserDetailsProvider","fragments":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"text":"UserDetailsProvider","kind":"identifier"}],"title":"UserDetailsProvider","role":"symbol","type":"topic","abstract":[{"type":"text","text":"A provider providing user display information to the SDK"}],"navigatorTitle":[{"kind":"identifier","text":"UserDetailsProvider"}],"kind":"symbol","url":"\/documentation\/kaleyravideosdk\/userdetailsprovider"},"doc://com.kaleyra.KaleyraVideoSDK/documentation/KaleyraVideoSDK/KaleyraVideoSDKVersionNumber":{"abstract":[{"text":":nodoc:","type":"text"}],"role":"symbol","fragments":[{"kind":"identifier","text":"KaleyraVideoSDKVersionNumber"}],"type":"topic","kind":"symbol","identifier":"doc:\/\/com.kaleyra.KaleyraVideoSDK\/documentation\/KaleyraVideoSDK\/KaleyraVideoSDKVersionNumber","url":"\/documentation\/kaleyravideosdk\/kaleyravideosdkversionnumber","title":"KaleyraVideoSDKVersionNumber"},"doc://com.kaleyra.KaleyraVideoSDK/documentation/KaleyraVideoSDK/AppGroupIdentifier":{"title":"AppGroupIdentifier","fragments":[{"kind":"keyword","text":"struct"},{"text":" ","kind":"text"},{"text":"AppGroupIdentifier","kind":"identifier"}],"kind":"symbol","abstract":[{"type":"text","text":"A value representing an App group identifier"}],"navigatorTitle":[{"kind":"identifier","text":"AppGroupIdentifier"}],"type":"topic","url":"\/documentation\/kaleyravideosdk\/appgroupidentifier","role":"symbol","identifier":"doc:\/\/com.kaleyra.KaleyraVideoSDK\/documentation\/KaleyraVideoSDK\/AppGroupIdentifier"},"doc://com.kaleyra.KaleyraVideoSDK/documentation/KaleyraVideoSDK/ChatNotification":{"abstract":[{"type":"text","text":"A value representing a chat notification."}],"url":"\/documentation\/kaleyravideosdk\/chatnotification","fragments":[{"kind":"keyword","text":"struct"},{"text":" ","kind":"text"},{"text":"ChatNotification","kind":"identifier"}],"role":"symbol","navigatorTitle":[{"text":"ChatNotification","kind":"identifier"}],"kind":"symbol","type":"topic","identifier":"doc:\/\/com.kaleyra.KaleyraVideoSDK\/documentation\/KaleyraVideoSDK\/ChatNotification","title":"ChatNotification"},"doc://com.kaleyra.KaleyraVideoSDK/documentation/KaleyraVideoSDK/CallParticipant":{"identifier":"doc:\/\/com.kaleyra.KaleyraVideoSDK\/documentation\/KaleyraVideoSDK\/CallParticipant","navigatorTitle":[{"text":"CallParticipant","kind":"identifier"}],"title":"CallParticipant","fragments":[{"text":"protocol","kind":"keyword"},{"kind":"text","text":" "},{"text":"CallParticipant","kind":"identifier"}],"type":"topic","abstract":[{"type":"text","text":"Object representing a call participant and its state in the call."}],"kind":"symbol","role":"symbol","url":"\/documentation\/kaleyravideosdk\/callparticipant"},"doc://com.kaleyra.KaleyraVideoSDK/documentation/KaleyraVideoSDK/KaleyraVideo":{"url":"\/documentation\/kaleyravideosdk\/kaleyravideo","fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"KaleyraVideo"}],"kind":"symbol","title":"KaleyraVideo","type":"topic","navigatorTitle":[{"kind":"identifier","text":"KaleyraVideo"}],"role":"symbol","identifier":"doc:\/\/com.kaleyra.KaleyraVideoSDK\/documentation\/KaleyraVideoSDK\/KaleyraVideo","abstract":[{"text":"The Kaleyra Video SDK entry point.","type":"text"}]},"doc://com.kaleyra.KaleyraVideoSDK/documentation/KaleyraVideoSDK/CallRecording":{"title":"CallRecording","kind":"symbol","identifier":"doc:\/\/com.kaleyra.KaleyraVideoSDK\/documentation\/KaleyraVideoSDK\/CallRecording","navigatorTitle":[{"kind":"identifier","text":"CallRecording"}],"role":"symbol","abstract":[{"text":"A class representing the recording of a call","type":"text"}],"fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"text":"CallRecording","kind":"identifier"}],"type":"topic","url":"\/documentation\/kaleyravideosdk\/callrecording"},"doc://com.kaleyra.KaleyraVideoSDK/documentation/KaleyraVideoSDK/Call":{"identifier":"doc:\/\/com.kaleyra.KaleyraVideoSDK\/documentation\/KaleyraVideoSDK\/Call","kind":"symbol","fragments":[{"kind":"keyword","text":"protocol"},{"text":" ","kind":"text"},{"text":"Call","kind":"identifier"}],"title":"Call","role":"symbol","type":"topic","abstract":[{"type":"text","text":"An object representing a Kaleyra Video VoIP call."}],"url":"\/documentation\/kaleyravideosdk\/call","navigatorTitle":[{"kind":"identifier","text":"Call"}]},"doc://com.kaleyra.KaleyraVideoSDK/documentation/KaleyraVideoSDK/CallParticipantState":{"identifier":"doc:\/\/com.kaleyra.KaleyraVideoSDK\/documentation\/KaleyraVideoSDK\/CallParticipantState","role":"symbol","url":"\/documentation\/kaleyravideosdk\/callparticipantstate","type":"topic","navigatorTitle":[{"text":"CallParticipantState","kind":"identifier"}],"abstract":[{"type":"text","text":"An enumeration representing the states a participant can be in, during a call."}],"fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"CallParticipantState"}],"kind":"symbol","title":"CallParticipantState"},"doc://com.kaleyra.KaleyraVideoSDK/documentation/KaleyraVideoSDK/ConferenceSettings":{"url":"\/documentation\/kaleyravideosdk\/conferencesettings","fragments":[{"kind":"keyword","text":"struct"},{"kind":"text","text":" "},{"kind":"identifier","text":"ConferenceSettings"}],"type":"topic","kind":"symbol","title":"ConferenceSettings","navigatorTitle":[{"text":"ConferenceSettings","kind":"identifier"}],"role":"symbol","identifier":"doc:\/\/com.kaleyra.KaleyraVideoSDK\/documentation\/KaleyraVideoSDK\/ConferenceSettings","abstract":[{"text":"A value representing the settings used when a call is created or received.","type":"text"}]},"doc://com.kaleyra.KaleyraVideoSDK/documentation/KaleyraVideoSDK/ClientState":{"kind":"symbol","identifier":"doc:\/\/com.kaleyra.KaleyraVideoSDK\/documentation\/KaleyraVideoSDK\/ClientState","type":"topic","role":"symbol","fragments":[{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"text":"ClientState","kind":"identifier"}],"abstract":[{"type":"text","text":"An enumeration representing the states a client can be in."}],"url":"\/documentation\/kaleyravideosdk\/clientstate","navigatorTitle":[{"kind":"identifier","text":"ClientState"}],"title":"ClientState"},"doc://com.kaleyra.KaleyraVideoSDK/documentation/KaleyraVideoSDK/LogLevel":{"kind":"symbol","type":"topic","url":"\/documentation\/kaleyravideosdk\/loglevel","title":"LogLevel","fragments":[{"text":"enum","kind":"keyword"},{"kind":"text","text":" "},{"text":"LogLevel","kind":"identifier"}],"role":"symbol","identifier":"doc:\/\/com.kaleyra.KaleyraVideoSDK\/documentation\/KaleyraVideoSDK\/LogLevel","abstract":[{"text":"Log levels are used to filter out logs. You can choose which level of logging filter you want to select using the ","type":"text"},{"type":"codeVoice","code":"KaleyraVideoSDK.logLevel"},{"type":"text","text":" property"}],"navigatorTitle":[{"text":"LogLevel","kind":"identifier"}]},"doc://com.kaleyra.KaleyraVideoSDK/documentation/KaleyraVideoSDK/Environment":{"url":"\/documentation\/kaleyravideosdk\/environment","fragments":[{"kind":"keyword","text":"struct"},{"kind":"text","text":" "},{"kind":"identifier","text":"Environment"}],"type":"topic","kind":"symbol","title":"Environment","navigatorTitle":[{"text":"Environment","kind":"identifier"}],"role":"symbol","identifier":"doc:\/\/com.kaleyra.KaleyraVideoSDK\/documentation\/KaleyraVideoSDK\/Environment","abstract":[{"text":"Represents the back-end environment the SDK should connect to.","type":"text"}]},"doc://com.kaleyra.KaleyraVideoSDK/documentation/KaleyraVideoSDK/Config":{"url":"\/documentation\/kaleyravideosdk\/config","fragments":[{"text":"struct","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"Config"}],"kind":"symbol","title":"Config","type":"topic","navigatorTitle":[{"kind":"identifier","text":"Config"}],"role":"symbol","identifier":"doc:\/\/com.kaleyra.KaleyraVideoSDK\/documentation\/KaleyraVideoSDK\/Config","abstract":[{"text":"A value encapsulating the configuration options for the Kaleyra Video SDK.","type":"text"}]},"doc://com.kaleyra.KaleyraVideoSDK/documentation/KaleyraVideoSDK/InAppNotificationsDelegate":{"abstract":[{"text":"Represents a chat notification touch listener","type":"text"}],"url":"\/documentation\/kaleyravideosdk\/inappnotificationsdelegate","fragments":[{"text":"protocol","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"InAppNotificationsDelegate"}],"role":"symbol","navigatorTitle":[{"kind":"identifier","text":"InAppNotificationsDelegate"}],"kind":"symbol","type":"topic","identifier":"doc:\/\/com.kaleyra.KaleyraVideoSDK\/documentation\/KaleyraVideoSDK\/InAppNotificationsDelegate","title":"InAppNotificationsDelegate"},"doc://com.kaleyra.KaleyraVideoSDK/documentation/KaleyraVideoSDK/InAppNotifications":{"kind":"symbol","navigatorTitle":[{"kind":"identifier","text":"InAppNotifications"}],"abstract":[{"type":"text","text":"Represents the central coordination point for in-app notifications."}],"title":"InAppNotifications","url":"\/documentation\/kaleyravideosdk\/inappnotifications","type":"topic","identifier":"doc:\/\/com.kaleyra.KaleyraVideoSDK\/documentation\/KaleyraVideoSDK\/InAppNotifications","role":"symbol","fragments":[{"kind":"keyword","text":"protocol"},{"text":" ","kind":"text"},{"text":"InAppNotifications","kind":"identifier"}]},"doc://com.kaleyra.KaleyraVideoSDK/documentation/KaleyraVideoSDK":{"title":"KaleyraVideoSDK","type":"topic","identifier":"doc:\/\/com.kaleyra.KaleyraVideoSDK\/documentation\/KaleyraVideoSDK","role":"collection","abstract":[],"kind":"symbol","url":"\/documentation\/kaleyravideosdk"},"doc://com.kaleyra.KaleyraVideoSDK/documentation/KaleyraVideoSDK/CallViewControllerDelegate":{"url":"\/documentation\/kaleyravideosdk\/callviewcontrollerdelegate","fragments":[{"text":"protocol","kind":"keyword"},{"text":" ","kind":"text"},{"text":"CallViewControllerDelegate","kind":"identifier"}],"title":"CallViewControllerDelegate","kind":"symbol","role":"symbol","type":"topic","navigatorTitle":[{"text":"CallViewControllerDelegate","kind":"identifier"}],"abstract":[{"type":"text","text":"Represents the delegate of a "},{"isActive":true,"type":"reference","identifier":"doc:\/\/com.kaleyra.KaleyraVideoSDK\/documentation\/KaleyraVideoSDK\/CallViewController"},{"text":" instance.","type":"text"}],"identifier":"doc:\/\/com.kaleyra.KaleyraVideoSDK\/documentation\/KaleyraVideoSDK\/CallViewControllerDelegate"},"doc://com.kaleyra.KaleyraVideoSDK/documentation/KaleyraVideoSDK/Region":{"role":"symbol","type":"topic","abstract":[{"type":"text","text":"Represents the Region in the world where users’ data is stored"}],"url":"\/documentation\/kaleyravideosdk\/region","fragments":[{"text":"struct","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"Region"}],"identifier":"doc:\/\/com.kaleyra.KaleyraVideoSDK\/documentation\/KaleyraVideoSDK\/Region","navigatorTitle":[{"text":"Region","kind":"identifier"}],"title":"Region","kind":"symbol"},"doc://com.kaleyra.KaleyraVideoSDK/documentation/KaleyraVideoSDK/Theme":{"identifier":"doc:\/\/com.kaleyra.KaleyraVideoSDK\/documentation\/KaleyraVideoSDK\/Theme","title":"Theme","url":"\/documentation\/kaleyravideosdk\/theme","role":"symbol","abstract":[{"text":"A value holding UI customization values.","type":"text"}],"navigatorTitle":[{"kind":"identifier","text":"Theme"}],"kind":"symbol","fragments":[{"text":"struct","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"Theme"}],"type":"topic"},"doc://com.kaleyra.KaleyraVideoSDK/documentation/KaleyraVideoSDK/ChatViewControllerDelegate":{"identifier":"doc:\/\/com.kaleyra.KaleyraVideoSDK\/documentation\/KaleyraVideoSDK\/ChatViewControllerDelegate","role":"symbol","title":"ChatViewControllerDelegate","navigatorTitle":[{"kind":"identifier","text":"ChatViewControllerDelegate"}],"type":"topic","kind":"symbol","abstract":[{"type":"text","text":"Represents the "},{"isActive":true,"identifier":"doc:\/\/com.kaleyra.KaleyraVideoSDK\/documentation\/KaleyraVideoSDK\/ChatViewController","type":"reference"},{"type":"text","text":"’s delegate."}],"fragments":[{"text":"protocol","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"ChatViewControllerDelegate"}],"url":"\/documentation\/kaleyravideosdk\/chatviewcontrollerdelegate"},"doc://com.kaleyra.KaleyraVideoSDK/documentation/KaleyraVideoSDK/CallState":{"navigatorTitle":[{"kind":"identifier","text":"CallState"}],"role":"symbol","title":"CallState","fragments":[{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"CallState"}],"url":"\/documentation\/kaleyravideosdk\/callstate","identifier":"doc:\/\/com.kaleyra.KaleyraVideoSDK\/documentation\/KaleyraVideoSDK\/CallState","type":"topic","kind":"symbol","abstract":[{"text":"An enumeration representing the states a call can be in.","type":"text"}]},"doc://com.kaleyra.KaleyraVideoSDK/documentation/KaleyraVideoSDK/KaleyraVideoSDKVersionString":{"abstract":[{"text":":nodoc:","type":"text"}],"role":"symbol","fragments":[{"text":"KaleyraVideoSDKVersionString","kind":"identifier"}],"type":"topic","identifier":"doc:\/\/com.kaleyra.KaleyraVideoSDK\/documentation\/KaleyraVideoSDK\/KaleyraVideoSDKVersionString","kind":"symbol","url":"\/documentation\/kaleyravideosdk\/kaleyravideosdkversionstring","title":"KaleyraVideoSDKVersionString"},"doc://com.kaleyra.KaleyraVideoSDK/documentation/KaleyraVideoSDK/CallViewController":{"role":"symbol","kind":"symbol","type":"topic","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"text":"CallViewController","kind":"identifier"}],"title":"CallViewController","abstract":[{"type":"text","text":"A view controller showing a call user interface"}],"url":"\/documentation\/kaleyravideosdk\/callviewcontroller","identifier":"doc:\/\/com.kaleyra.KaleyraVideoSDK\/documentation\/KaleyraVideoSDK\/CallViewController","navigatorTitle":[{"kind":"identifier","text":"CallViewController"}]},"doc://com.kaleyra.KaleyraVideoSDK/documentation/KaleyraVideoSDK/VoIPCredentials":{"url":"\/documentation\/kaleyravideosdk\/voipcredentials","fragments":[{"text":"struct","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"VoIPCredentials"}],"title":"VoIPCredentials","kind":"symbol","role":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"VoIPCredentials"}],"abstract":[{"text":"A value holding the VoIP device push token","type":"text"}],"identifier":"doc:\/\/com.kaleyra.KaleyraVideoSDK\/documentation\/KaleyraVideoSDK\/VoIPCredentials"},"doc://com.kaleyra.KaleyraVideoSDK/documentation/KaleyraVideoSDK/CallWindow":{"title":"CallWindow","identifier":"doc:\/\/com.kaleyra.KaleyraVideoSDK\/documentation\/KaleyraVideoSDK\/CallWindow","fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"kind":"identifier","text":"CallWindow"}],"kind":"symbol","url":"\/documentation\/kaleyravideosdk\/callwindow","role":"symbol","type":"topic","abstract":[{"text":"A window presenting its root view controller animated.","type":"text"}],"navigatorTitle":[{"kind":"identifier","text":"CallWindow"}]},"doc://com.kaleyra.KaleyraVideoSDK/documentation/KaleyraVideoSDK/UserDetails":{"identifier":"doc:\/\/com.kaleyra.KaleyraVideoSDK\/documentation\/KaleyraVideoSDK\/UserDetails","fragments":[{"kind":"keyword","text":"struct"},{"text":" ","kind":"text"},{"kind":"identifier","text":"UserDetails"}],"title":"UserDetails","role":"symbol","type":"topic","abstract":[{"text":"A value holding an user’s profile information.","type":"text"}],"navigatorTitle":[{"text":"UserDetails","kind":"identifier"}],"kind":"symbol","url":"\/documentation\/kaleyravideosdk\/userdetails"},"doc://com.kaleyra.KaleyraVideoSDK/documentation/KaleyraVideoSDK/ChatViewController":{"navigatorTitle":[{"kind":"identifier","text":"ChatViewController"}],"url":"\/documentation\/kaleyravideosdk\/chatviewcontroller","type":"topic","title":"ChatViewController","identifier":"doc:\/\/com.kaleyra.KaleyraVideoSDK\/documentation\/KaleyraVideoSDK\/ChatViewController","kind":"symbol","role":"symbol","abstract":[{"type":"text","text":"A view controller showing the user interface of a chat."}],"fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"ChatViewController"}]},"doc://com.kaleyra.KaleyraVideoSDK/documentation/KaleyraVideoSDK/LogFlag":{"role":"symbol","kind":"symbol","url":"\/documentation\/kaleyravideosdk\/logflag","identifier":"doc:\/\/com.kaleyra.KaleyraVideoSDK\/documentation\/KaleyraVideoSDK\/LogFlag","fragments":[{"kind":"keyword","text":"enum"},{"text":" ","kind":"text"},{"text":"LogFlag","kind":"identifier"}],"navigatorTitle":[{"kind":"identifier","text":"LogFlag"}],"title":"LogFlag","type":"topic","abstract":[{"text":"Log flags.. They are used together with levels to filter out logs.","type":"text"}]}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","value":"occ","path":"\/identifier\/interfaceLanguage"},{"value":[{"title":"Classes","identifiers":["doc:\/\/com.kaleyra.KaleyraVideoSDK\/documentation\/KaleyraVideoSDK\/CallViewController","doc:\/\/com.kaleyra.KaleyraVideoSDK\/documentation\/KaleyraVideoSDK\/CallWindow","doc:\/\/com.kaleyra.KaleyraVideoSDK\/documentation\/KaleyraVideoSDK\/ChatViewController"]},{"title":"Variables","identifiers":["doc:\/\/com.kaleyra.KaleyraVideoSDK\/documentation\/KaleyraVideoSDK\/KaleyraVideoSDKVersionNumber","doc:\/\/com.kaleyra.KaleyraVideoSDK\/documentation\/KaleyraVideoSDK\/KaleyraVideoSDKVersionString"]}],"op":"replace","path":"\/topicSections"},{"op":"add","value":null,"path":"\/relationshipsSections"},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/references\/doc:~1~1com.kaleyra.KaleyraVideoSDK~1documentation~1KaleyraVideoSDK~1CallViewController\/title","value":"CallViewController"},{"op":"replace","path":"\/references\/doc:~1~1com.kaleyra.KaleyraVideoSDK~1documentation~1KaleyraVideoSDK~1CallViewController\/fragments","value":[{"kind":"identifier","text":"CallViewController"}]},{"op":"replace","value":"CallWindow","path":"\/references\/doc:~1~1com.kaleyra.KaleyraVideoSDK~1documentation~1KaleyraVideoSDK~1CallWindow\/title"},{"path":"\/references\/doc:~1~1com.kaleyra.KaleyraVideoSDK~1documentation~1KaleyraVideoSDK~1CallWindow\/fragments","op":"replace","value":[{"text":"CallWindow","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1com.kaleyra.KaleyraVideoSDK~1documentation~1KaleyraVideoSDK~1ChatViewController\/title","value":"ChatViewController"},{"value":[{"kind":"identifier","text":"ChatViewController"}],"op":"replace","path":"\/references\/doc:~1~1com.kaleyra.KaleyraVideoSDK~1documentation~1KaleyraVideoSDK~1ChatViewController\/fragments"}]}]}