{"hierarchy":{"paths":[["doc:\/\/com.kaleyra.KaleyraVideoSDK\/documentation\/KaleyraVideoSDK"]]},"primaryContentSections":[{"declarations":[{"platforms":["iOS"],"languages":["swift"],"tokens":[{"kind":"keyword","text":"final"},{"kind":"text","text":" "},{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"ChatViewController","kind":"identifier"}]}],"kind":"declarations"},{"kind":"content","content":[{"level":2,"text":"Overview","type":"heading","anchor":"overview"},{"type":"paragraph","inlineContent":[{"text":"This view controller should be presented modally. You should not embed this view controller in a ","type":"text"},{"code":"UINavigationController","type":"codeVoice"},{"type":"text","text":"."}]},{"content":[{"inlineContent":[{"text":"4.0.0","type":"text"}],"type":"paragraph"}],"style":"note","name":"Since","type":"aside"}]}],"relationshipsSections":[{"type":"inheritsFrom","identifiers":["doc:\/\/com.kaleyra.KaleyraVideoSDK\/objc(cs)UIViewController"],"title":"Inherits From","kind":"relationships"},{"kind":"relationships","type":"conformsTo","identifiers":["doc:\/\/com.kaleyra.KaleyraVideoSDK\/objc(pl)NSCoding","doc:\/\/com.kaleyra.KaleyraVideoSDK\/objc(pl)NSExtensionRequestHandling","doc:\/\/com.kaleyra.KaleyraVideoSDK\/17KaleyraFoundation21PropertyProxyProviderP","doc:\/\/com.kaleyra.KaleyraVideoSDK\/17KaleyraFoundation18SubscriptionsOwnerP","doc:\/\/com.kaleyra.KaleyraVideoSDK\/objc(pl)NSObject","doc:\/\/com.kaleyra.KaleyraVideoSDK\/s7CVarArgP","doc:\/\/com.kaleyra.KaleyraVideoSDK\/s28CustomDebugStringConvertibleP","doc:\/\/com.kaleyra.KaleyraVideoSDK\/s23CustomStringConvertibleP","doc:\/\/com.kaleyra.KaleyraVideoSDK\/SQ","doc:\/\/com.kaleyra.KaleyraVideoSDK\/SH","doc:\/\/com.kaleyra.KaleyraVideoSDK\/s8SendableP","doc:\/\/com.kaleyra.KaleyraVideoSDK\/objc(pl)UIActivityItemsConfigurationProviding","doc:\/\/com.kaleyra.KaleyraVideoSDK\/objc(pl)UIAppearanceContainer","doc:\/\/com.kaleyra.KaleyraVideoSDK\/objc(pl)UIBarPositioningDelegate","doc:\/\/com.kaleyra.KaleyraVideoSDK\/objc(pl)UIContentContainer","doc:\/\/com.kaleyra.KaleyraVideoSDK\/objc(pl)UIFocusEnvironment","doc:\/\/com.kaleyra.KaleyraVideoSDK\/objc(pl)UINavigationBarDelegate","doc:\/\/com.kaleyra.KaleyraVideoSDK\/objc(pl)UIPasteConfigurationSupporting","doc:\/\/com.kaleyra.KaleyraVideoSDK\/objc(pl)UIResponderStandardEditActions","doc:\/\/com.kaleyra.KaleyraVideoSDK\/objc(pl)UIStateRestoring","doc:\/\/com.kaleyra.KaleyraVideoSDK\/5UIKit23UITraitChangeObservableP","doc:\/\/com.kaleyra.KaleyraVideoSDK\/objc(pl)UITraitEnvironment","doc:\/\/com.kaleyra.KaleyraVideoSDK\/objc(pl)UIUserActivityRestoring"],"title":"Conforms To"}],"schemaVersion":{"minor":3,"patch":0,"major":0},"abstract":[{"type":"text","text":"A view controller showing the user interface of a chat."}],"kind":"symbol","sections":[],"metadata":{"externalID":"c:@M@KaleyraVideoSDK@objc(cs)ChatViewController","role":"symbol","roleHeading":"Class","title":"ChatViewController","symbolKind":"class","fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"text":"ChatViewController","kind":"identifier"}],"navigatorTitle":[{"kind":"identifier","text":"ChatViewController"}],"modules":[{"name":"KaleyraVideoSDK"}],"platforms":[{"beta":false,"deprecated":false,"name":"iOS","introducedAt":"15.0","unavailable":false}]},"identifier":{"url":"doc:\/\/com.kaleyra.KaleyraVideoSDK\/documentation\/KaleyraVideoSDK\/ChatViewController","interfaceLanguage":"swift"},"topicSections":[{"identifiers":["doc:\/\/com.kaleyra.KaleyraVideoSDK\/documentation\/KaleyraVideoSDK\/ChatViewController\/Configuration-swift.struct"],"title":"Structures"},{"identifiers":["doc:\/\/com.kaleyra.KaleyraVideoSDK\/documentation\/KaleyraVideoSDK\/ChatViewController\/init(intent:configuration:)"],"title":"Initializers"},{"identifiers":["doc:\/\/com.kaleyra.KaleyraVideoSDK\/documentation\/KaleyraVideoSDK\/ChatViewController\/chatId","doc:\/\/com.kaleyra.KaleyraVideoSDK\/documentation\/KaleyraVideoSDK\/ChatViewController\/configuration-swift.property","doc:\/\/com.kaleyra.KaleyraVideoSDK\/documentation\/KaleyraVideoSDK\/ChatViewController\/delegate","doc:\/\/com.kaleyra.KaleyraVideoSDK\/documentation\/KaleyraVideoSDK\/ChatViewController\/participants"],"title":"Instance Properties"},{"identifiers":["doc:\/\/com.kaleyra.KaleyraVideoSDK\/documentation\/KaleyraVideoSDK\/ChatViewController\/Intent"],"title":"Enumerations"},{"generated":true,"title":"Default Implementations","identifiers":["doc:\/\/com.kaleyra.KaleyraVideoSDK\/documentation\/KaleyraVideoSDK\/ChatViewController\/UIBarPositioningDelegate-Implementations"]}],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/kaleyravideosdk\/chatviewcontroller"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/kaleyravideosdk\/chatviewcontroller"]}],"references":{"doc://com.kaleyra.KaleyraVideoSDK/objc(pl)UIFocusEnvironment":{"type":"unresolvable","identifier":"doc:\/\/com.kaleyra.KaleyraVideoSDK\/objc(pl)UIFocusEnvironment","title":"UIKit.UIFocusEnvironment"},"doc://com.kaleyra.KaleyraVideoSDK/documentation/KaleyraVideoSDK/ChatViewController/configuration-swift.property":{"abstract":[{"type":"text","text":"The "},{"isActive":true,"type":"reference","identifier":"doc:\/\/com.kaleyra.KaleyraVideoSDK\/documentation\/KaleyraVideoSDK\/ChatViewController\/Configuration-swift.struct"},{"type":"text","text":" used to configure this view controller."}],"title":"configuration","identifier":"doc:\/\/com.kaleyra.KaleyraVideoSDK\/documentation\/KaleyraVideoSDK\/ChatViewController\/configuration-swift.property","role":"symbol","kind":"symbol","fragments":[{"kind":"keyword","text":"let"},{"kind":"text","text":" "},{"kind":"identifier","text":"configuration"},{"kind":"text","text":": "},{"text":"ChatViewController","kind":"typeIdentifier","preciseIdentifier":"c:@M@KaleyraVideoSDK@objc(cs)ChatViewController"},{"kind":"text","text":"."},{"kind":"typeIdentifier","text":"Configuration","preciseIdentifier":"s:15KaleyraVideoSDK18ChatViewControllerC13ConfigurationV"}],"type":"topic","url":"\/documentation\/kaleyravideosdk\/chatviewcontroller\/configuration-swift.property"},"doc://com.kaleyra.KaleyraVideoSDK/documentation/KaleyraVideoSDK/ChatViewController/chatId":{"abstract":[{"type":"text","text":"The id of the chat displayed by this controller"}],"title":"chatId","identifier":"doc:\/\/com.kaleyra.KaleyraVideoSDK\/documentation\/KaleyraVideoSDK\/ChatViewController\/chatId","role":"symbol","kind":"symbol","fragments":[{"kind":"keyword","text":"var"},{"text":" ","kind":"text"},{"kind":"identifier","text":"chatId"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"s:SS","text":"String"},{"kind":"text","text":"?"}],"type":"topic","url":"\/documentation\/kaleyravideosdk\/chatviewcontroller\/chatid"},"doc://com.kaleyra.KaleyraVideoSDK/s28CustomDebugStringConvertibleP":{"type":"unresolvable","title":"Swift.CustomDebugStringConvertible","identifier":"doc:\/\/com.kaleyra.KaleyraVideoSDK\/s28CustomDebugStringConvertibleP"},"doc://com.kaleyra.KaleyraVideoSDK/documentation/KaleyraVideoSDK/ChatViewController/viewDidLayoutSubviews":{"abstract":[],"title":"viewDidLayoutSubviews","identifier":"doc:\/\/com.kaleyra.KaleyraVideoSDK\/documentation\/KaleyraVideoSDK\/ChatViewController\/viewDidLayoutSubviews","role":"symbol","kind":"symbol","navigatorTitle":[{"kind":"identifier","text":"viewDidLayoutSubviews"}],"fragments":[{"kind":"text","text":"- "},{"kind":"identifier","text":"viewDidLayoutSubviews"}],"type":"topic","url":"\/documentation\/kaleyravideosdk\/chatviewcontroller\/viewdidlayoutsubviews"},"doc://com.kaleyra.KaleyraVideoSDK/documentation/KaleyraVideoSDK/ChatViewController/participants":{"abstract":[{"type":"text","text":"The ids of the participants belonging to the chat channel being displayed."}],"title":"participants","identifier":"doc:\/\/com.kaleyra.KaleyraVideoSDK\/documentation\/KaleyraVideoSDK\/ChatViewController\/participants","role":"symbol","kind":"symbol","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"participants"},{"text":": [","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"s:SS","text":"String"},{"kind":"text","text":"]"}],"type":"topic","url":"\/documentation\/kaleyravideosdk\/chatviewcontroller\/participants"},"doc://com.kaleyra.KaleyraVideoSDK/objc(pl)NSObject":{"type":"unresolvable","identifier":"doc:\/\/com.kaleyra.KaleyraVideoSDK\/objc(pl)NSObject","title":"ObjectiveC.NSObjectProtocol"},"doc://com.kaleyra.KaleyraVideoSDK/documentation/KaleyraVideoSDK/ChatViewController/Intent":{"abstract":[{"type":"text","text":"A value representing the chat you want to be shown by the view controller."}],"fragments":[{"kind":"keyword","text":"enum"},{"text":" ","kind":"text"},{"kind":"identifier","text":"Intent"}],"kind":"symbol","type":"topic","title":"ChatViewController.Intent","role":"symbol","identifier":"doc:\/\/com.kaleyra.KaleyraVideoSDK\/documentation\/KaleyraVideoSDK\/ChatViewController\/Intent","navigatorTitle":[{"text":"Intent","kind":"identifier"}],"url":"\/documentation\/kaleyravideosdk\/chatviewcontroller\/intent"},"doc://com.kaleyra.KaleyraVideoSDK/documentation/KaleyraVideoSDK/ChatViewController/init(intent:configuration:)":{"abstract":[{"type":"text","text":"Creates an instance bound to the Chat represented by the intent provided in initialisation"}],"title":"init(intent:configuration:)","identifier":"doc:\/\/com.kaleyra.KaleyraVideoSDK\/documentation\/KaleyraVideoSDK\/ChatViewController\/init(intent:configuration:)","role":"symbol","kind":"symbol","fragments":[{"kind":"identifier","text":"init"},{"text":"(","kind":"text"},{"kind":"externalParam","text":"intent"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"s:15KaleyraVideoSDK18ChatViewControllerC6IntentO","text":"Intent"},{"kind":"text","text":", "},{"kind":"externalParam","text":"configuration"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:@M@KaleyraVideoSDK@objc(cs)ChatViewController","kind":"typeIdentifier","text":"ChatViewController"},{"kind":"text","text":"."},{"preciseIdentifier":"s:15KaleyraVideoSDK18ChatViewControllerC13ConfigurationV","text":"Configuration","kind":"typeIdentifier"},{"text":")","kind":"text"}],"type":"topic","url":"\/documentation\/kaleyravideosdk\/chatviewcontroller\/init(intent:configuration:)"},"doc://com.kaleyra.KaleyraVideoSDK/objc(pl)UIActivityItemsConfigurationProviding":{"type":"unresolvable","title":"UIKit.UIActivityItemsConfigurationProviding","identifier":"doc:\/\/com.kaleyra.KaleyraVideoSDK\/objc(pl)UIActivityItemsConfigurationProviding"},"doc://com.kaleyra.KaleyraVideoSDK/SQ":{"type":"unresolvable","title":"Swift.Equatable","identifier":"doc:\/\/com.kaleyra.KaleyraVideoSDK\/SQ"},"doc://com.kaleyra.KaleyraVideoSDK/objc(pl)UIStateRestoring":{"type":"unresolvable","title":"UIKit.UIStateRestoring","identifier":"doc:\/\/com.kaleyra.KaleyraVideoSDK\/objc(pl)UIStateRestoring"},"doc://com.kaleyra.KaleyraVideoSDK/s23CustomStringConvertibleP":{"type":"unresolvable","title":"Swift.CustomStringConvertible","identifier":"doc:\/\/com.kaleyra.KaleyraVideoSDK\/s23CustomStringConvertibleP"},"doc://com.kaleyra.KaleyraVideoSDK/documentation/KaleyraVideoSDK/ChatViewController/Configuration-swift.struct":{"navigatorTitle":[{"kind":"identifier","text":"Configuration"}],"identifier":"doc:\/\/com.kaleyra.KaleyraVideoSDK\/documentation\/KaleyraVideoSDK\/ChatViewController\/Configuration-swift.struct","type":"topic","abstract":[{"text":"A value holding the customization available for a ","type":"text"},{"identifier":"doc:\/\/com.kaleyra.KaleyraVideoSDK\/documentation\/KaleyraVideoSDK\/ChatViewController","isActive":true,"type":"reference"},{"type":"text","text":" instance."}],"role":"symbol","fragments":[{"kind":"keyword","text":"struct"},{"text":" ","kind":"text"},{"text":"Configuration","kind":"identifier"}],"url":"\/documentation\/kaleyravideosdk\/chatviewcontroller\/configuration-swift.struct","title":"ChatViewController.Configuration","kind":"symbol"},"doc://com.kaleyra.KaleyraVideoSDK/objc(pl)UIPasteConfigurationSupporting":{"type":"unresolvable","identifier":"doc:\/\/com.kaleyra.KaleyraVideoSDK\/objc(pl)UIPasteConfigurationSupporting","title":"UIKit.UIPasteConfigurationSupporting"},"doc://com.kaleyra.KaleyraVideoSDK/objc(pl)NSExtensionRequestHandling":{"type":"unresolvable","title":"Foundation.NSExtensionRequestHandling","identifier":"doc:\/\/com.kaleyra.KaleyraVideoSDK\/objc(pl)NSExtensionRequestHandling"},"doc://com.kaleyra.KaleyraVideoSDK/objc(pl)UIUserActivityRestoring":{"type":"unresolvable","title":"UIKit.UIUserActivityRestoring","identifier":"doc:\/\/com.kaleyra.KaleyraVideoSDK\/objc(pl)UIUserActivityRestoring"},"doc://com.kaleyra.KaleyraVideoSDK/documentation/KaleyraVideoSDK/ChatViewController/canBecomeFirstResponder":{"abstract":[],"title":"canBecomeFirstResponder","identifier":"doc:\/\/com.kaleyra.KaleyraVideoSDK\/documentation\/KaleyraVideoSDK\/ChatViewController\/canBecomeFirstResponder","role":"symbol","kind":"symbol","fragments":[{"text":"canBecomeFirstResponder","kind":"identifier"}],"type":"topic","url":"\/documentation\/kaleyravideosdk\/chatviewcontroller\/canbecomefirstresponder"},"doc://com.kaleyra.KaleyraVideoSDK/17KaleyraFoundation18SubscriptionsOwnerP":{"type":"unresolvable","identifier":"doc:\/\/com.kaleyra.KaleyraVideoSDK\/17KaleyraFoundation18SubscriptionsOwnerP","title":"KaleyraFoundation.SubscriptionsOwner"},"doc://com.kaleyra.KaleyraVideoSDK/documentation/KaleyraVideoSDK/ChatViewController/UIBarPositioningDelegate-Implementations":{"abstract":[],"kind":"article","type":"topic","title":"UIBarPositioningDelegate Implementations","role":"collectionGroup","identifier":"doc:\/\/com.kaleyra.KaleyraVideoSDK\/documentation\/KaleyraVideoSDK\/ChatViewController\/UIBarPositioningDelegate-Implementations","url":"\/documentation\/kaleyravideosdk\/chatviewcontroller\/uibarpositioningdelegate-implementations"},"doc://com.kaleyra.KaleyraVideoSDK/objc(pl)UITraitEnvironment":{"type":"unresolvable","title":"UIKit.UITraitEnvironment","identifier":"doc:\/\/com.kaleyra.KaleyraVideoSDK\/objc(pl)UITraitEnvironment"},"doc://com.kaleyra.KaleyraVideoSDK/5UIKit23UITraitChangeObservableP":{"type":"unresolvable","title":"UIKit.UITraitChangeObservable","identifier":"doc:\/\/com.kaleyra.KaleyraVideoSDK\/5UIKit23UITraitChangeObservableP"},"doc://com.kaleyra.KaleyraVideoSDK/s8SendableP":{"type":"unresolvable","identifier":"doc:\/\/com.kaleyra.KaleyraVideoSDK\/s8SendableP","title":"Swift.Sendable"},"doc://com.kaleyra.KaleyraVideoSDK/objc(pl)UIResponderStandardEditActions":{"type":"unresolvable","identifier":"doc:\/\/com.kaleyra.KaleyraVideoSDK\/objc(pl)UIResponderStandardEditActions","title":"UIKit.UIResponderStandardEditActions"},"doc://com.kaleyra.KaleyraVideoSDK/objc(pl)UIContentContainer":{"type":"unresolvable","title":"UIKit.UIContentContainer","identifier":"doc:\/\/com.kaleyra.KaleyraVideoSDK\/objc(pl)UIContentContainer"},"doc://com.kaleyra.KaleyraVideoSDK/SH":{"type":"unresolvable","title":"Swift.Hashable","identifier":"doc:\/\/com.kaleyra.KaleyraVideoSDK\/SH"},"doc://com.kaleyra.KaleyraVideoSDK/objc(cs)UIViewController":{"type":"unresolvable","title":"UIViewController","identifier":"doc:\/\/com.kaleyra.KaleyraVideoSDK\/objc(cs)UIViewController"},"doc://com.kaleyra.KaleyraVideoSDK/objc(pl)UIBarPositioningDelegate":{"type":"unresolvable","title":"UIKit.UIBarPositioningDelegate","identifier":"doc:\/\/com.kaleyra.KaleyraVideoSDK\/objc(pl)UIBarPositioningDelegate"},"doc://com.kaleyra.KaleyraVideoSDK/documentation/KaleyraVideoSDK/ChatViewController":{"abstract":[{"type":"text","text":"A view controller showing the user interface of a chat."}],"fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"kind":"identifier","text":"ChatViewController"}],"kind":"symbol","type":"topic","title":"ChatViewController","role":"symbol","identifier":"doc:\/\/com.kaleyra.KaleyraVideoSDK\/documentation\/KaleyraVideoSDK\/ChatViewController","navigatorTitle":[{"kind":"identifier","text":"ChatViewController"}],"url":"\/documentation\/kaleyravideosdk\/chatviewcontroller"},"doc://com.kaleyra.KaleyraVideoSDK/objc(pl)UIAppearanceContainer":{"type":"unresolvable","identifier":"doc:\/\/com.kaleyra.KaleyraVideoSDK\/objc(pl)UIAppearanceContainer","title":"UIKit.UIAppearanceContainer"},"doc://com.kaleyra.KaleyraVideoSDK/documentation/KaleyraVideoSDK/ChatViewController/delegate":{"abstract":[{"type":"text","text":"The view controller’s delegate."}],"title":"delegate","identifier":"doc:\/\/com.kaleyra.KaleyraVideoSDK\/documentation\/KaleyraVideoSDK\/ChatViewController\/delegate","role":"symbol","kind":"symbol","fragments":[{"text":"var","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"delegate"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","text":"ChatViewControllerDelegate","preciseIdentifier":"s:15KaleyraVideoSDK26ChatViewControllerDelegateP"},{"kind":"text","text":"?"}],"type":"topic","url":"\/documentation\/kaleyravideosdk\/chatviewcontroller\/delegate"},"doc://com.kaleyra.KaleyraVideoSDK/documentation/KaleyraVideoSDK/ChatViewController/viewDidLoad":{"role":"symbol","abstract":[],"identifier":"doc:\/\/com.kaleyra.KaleyraVideoSDK\/documentation\/KaleyraVideoSDK\/ChatViewController\/viewDidLoad","navigatorTitle":[{"kind":"identifier","text":"viewDidLoad"}],"title":"viewDidLoad","url":"\/documentation\/kaleyravideosdk\/chatviewcontroller\/viewdidload","fragments":[{"kind":"text","text":"- "},{"kind":"identifier","text":"viewDidLoad"}],"type":"topic","kind":"symbol"},"doc://com.kaleyra.KaleyraVideoSDK/s7CVarArgP":{"type":"unresolvable","title":"Swift.CVarArg","identifier":"doc:\/\/com.kaleyra.KaleyraVideoSDK\/s7CVarArgP"},"doc://com.kaleyra.KaleyraVideoSDK/objc(pl)NSCoding":{"type":"unresolvable","title":"Foundation.NSCoding","identifier":"doc:\/\/com.kaleyra.KaleyraVideoSDK\/objc(pl)NSCoding"},"doc://com.kaleyra.KaleyraVideoSDK/objc(pl)UINavigationBarDelegate":{"type":"unresolvable","title":"UINavigationBarDelegate","identifier":"doc:\/\/com.kaleyra.KaleyraVideoSDK\/objc(pl)UINavigationBarDelegate"},"doc://com.kaleyra.KaleyraVideoSDK/17KaleyraFoundation21PropertyProxyProviderP":{"type":"unresolvable","title":"KaleyraFoundation.PropertyProxyProvider","identifier":"doc:\/\/com.kaleyra.KaleyraVideoSDK\/17KaleyraFoundation21PropertyProxyProviderP"},"doc://com.kaleyra.KaleyraVideoSDK/documentation/KaleyraVideoSDK":{"kind":"symbol","type":"topic","url":"\/documentation\/kaleyravideosdk","abstract":[],"role":"collection","identifier":"doc:\/\/com.kaleyra.KaleyraVideoSDK\/documentation\/KaleyraVideoSDK","title":"KaleyraVideoSDK"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"path":"\/metadata\/platforms","value":[{"introducedAt":"15.0","unavailable":false,"beta":false,"deprecated":false,"name":"iOS"}],"op":"replace"},{"path":"\/metadata\/roleHeading","value":"Class","op":"replace"},{"path":"\/metadata\/title","op":"replace","value":"ChatViewController"},{"value":"class","path":"\/metadata\/symbolKind","op":"replace"},{"value":[{"text":"ChatViewController","kind":"identifier"}],"op":"replace","path":"\/metadata\/fragments"},{"value":[{"kind":"identifier","text":"ChatViewController"}],"op":"replace","path":"\/metadata\/navigatorTitle"},{"path":"\/topicSections","value":[{"title":"Instance Properties","identifiers":["doc:\/\/com.kaleyra.KaleyraVideoSDK\/documentation\/KaleyraVideoSDK\/ChatViewController\/canBecomeFirstResponder"]},{"identifiers":["doc:\/\/com.kaleyra.KaleyraVideoSDK\/documentation\/KaleyraVideoSDK\/ChatViewController\/viewDidLayoutSubviews","doc:\/\/com.kaleyra.KaleyraVideoSDK\/documentation\/KaleyraVideoSDK\/ChatViewController\/viewDidLoad"],"title":"Instance Methods"},{"generated":true,"title":"Default Implementations","identifiers":["doc:\/\/com.kaleyra.KaleyraVideoSDK\/documentation\/KaleyraVideoSDK\/ChatViewController\/UIBarPositioningDelegate-Implementations"]}],"op":"replace"},{"op":"replace","value":[{"title":"Inherits From","identifiers":["doc:\/\/com.kaleyra.KaleyraVideoSDK\/objc(cs)UIViewController"],"type":"inheritsFrom","kind":"relationships"},{"title":"Conforms To","type":"conformsTo","identifiers":["doc:\/\/com.kaleyra.KaleyraVideoSDK\/objc(pl)UINavigationBarDelegate"],"kind":"relationships"}],"path":"\/relationshipsSections"},{"value":null,"path":"\/seeAlsoSections","op":"add"},{"op":"replace","path":"\/primaryContentSections\/0","value":{"declarations":[{"platforms":["iOS"],"languages":["occ"],"tokens":[{"text":"@interface","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"ChatViewController"},{"kind":"text","text":" : "},{"text":"UIViewController","preciseIdentifier":"c:objc(cs)UIViewController","kind":"typeIdentifier"}]}],"kind":"declarations"}},{"op":"replace","value":"ChatViewController","path":"\/references\/doc:~1~1com.kaleyra.KaleyraVideoSDK~1documentation~1KaleyraVideoSDK~1ChatViewController\/title"},{"value":[{"text":"ChatViewController","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1com.kaleyra.KaleyraVideoSDK~1documentation~1KaleyraVideoSDK~1ChatViewController\/fragments"}]}]}