{"primaryContentSections":[{"kind":"declarations","declarations":[{"languages":["swift"],"platforms":["iOS"],"tokens":[{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"text":"position","kind":"identifier"},{"kind":"text","text":"("},{"kind":"externalParam","text":"for"},{"kind":"text","text":" "},{"kind":"internalParam","text":"bar"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:objc(pl)UIBarPositioning","kind":"typeIdentifier","text":"UIBarPositioning"},{"kind":"text","text":") -> "},{"preciseIdentifier":"c:@E@UIBarPosition","kind":"typeIdentifier","text":"UIBarPosition"}]}]}],"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/com.kaleyra.KaleyraVideoSDK\/documentation\/KaleyraVideoSDK\/ChannelViewController\/position(for:)"},"sections":[],"schemaVersion":{"major":0,"patch":0,"minor":3},"abstract":[{"text":"Inherited from ","type":"text"},{"code":"UIBarPositioningDelegate.position(for:)","type":"codeVoice"},{"text":".","type":"text"}],"hierarchy":{"paths":[["doc:\/\/com.kaleyra.KaleyraVideoSDK\/documentation\/KaleyraVideoSDK","doc:\/\/com.kaleyra.KaleyraVideoSDK\/documentation\/KaleyraVideoSDK\/ChannelViewController","doc:\/\/com.kaleyra.KaleyraVideoSDK\/documentation\/KaleyraVideoSDK\/ChannelViewController\/UIBarPositioningDelegate-Implementations"]]},"metadata":{"symbolKind":"method","role":"symbol","navigatorTitle":[{"text":"positionForBar:","kind":"identifier"}],"modules":[{"name":"KaleyraVideoSDK"}],"title":"position(for:)","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"position","kind":"identifier"},{"kind":"text","text":"("},{"text":"for","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"UIBarPositioning","kind":"typeIdentifier","preciseIdentifier":"c:objc(pl)UIBarPositioning"},{"text":") -> ","kind":"text"},{"text":"UIBarPosition","kind":"typeIdentifier","preciseIdentifier":"c:@E@UIBarPosition"}],"externalID":"c:@CM@KaleyraVideoSDK@objc(cs)ChannelViewController(im)positionForBar:","roleHeading":"Instance Method"},"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/kaleyravideosdk\/channelviewcontroller\/position(for:)"]},{"paths":["\/documentation\/kaleyravideosdk\/channelviewcontroller\/position(for:)"],"traits":[{"interfaceLanguage":"occ"}]}],"kind":"symbol","references":{"doc://com.kaleyra.KaleyraVideoSDK/documentation/KaleyraVideoSDK/ChannelViewController/UIBarPositioningDelegate-Implementations":{"role":"collectionGroup","kind":"article","abstract":[],"type":"topic","title":"UIBarPositioningDelegate Implementations","url":"\/documentation\/kaleyravideosdk\/channelviewcontroller\/uibarpositioningdelegate-implementations","identifier":"doc:\/\/com.kaleyra.KaleyraVideoSDK\/documentation\/KaleyraVideoSDK\/ChannelViewController\/UIBarPositioningDelegate-Implementations"},"doc://com.kaleyra.KaleyraVideoSDK/documentation/KaleyraVideoSDK":{"url":"\/documentation\/kaleyravideosdk","role":"collection","kind":"symbol","title":"KaleyraVideoSDK","abstract":[],"identifier":"doc:\/\/com.kaleyra.KaleyraVideoSDK\/documentation\/KaleyraVideoSDK","type":"topic"},"doc://com.kaleyra.KaleyraVideoSDK/documentation/KaleyraVideoSDK/ChannelViewController":{"navigatorTitle":[{"kind":"identifier","text":"ChannelViewController"}],"identifier":"doc:\/\/com.kaleyra.KaleyraVideoSDK\/documentation\/KaleyraVideoSDK\/ChannelViewController","url":"\/documentation\/kaleyravideosdk\/channelviewcontroller","abstract":[{"type":"text","text":"A view controller showing the user interface of a chat"}],"role":"symbol","title":"ChannelViewController","type":"topic","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"ChannelViewController"}],"kind":"symbol"},"doc://com.kaleyra.KaleyraVideoSDK/documentation/KaleyraVideoSDK/ChannelViewController/position(for:)":{"role":"symbol","navigatorTitle":[{"kind":"identifier","text":"positionForBar:"}],"abstract":[],"kind":"symbol","type":"topic","title":"position(for:)","url":"\/documentation\/kaleyravideosdk\/channelviewcontroller\/position(for:)","identifier":"doc:\/\/com.kaleyra.KaleyraVideoSDK\/documentation\/KaleyraVideoSDK\/ChannelViewController\/position(for:)","fragments":[{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"text":"position","kind":"identifier"},{"kind":"text","text":"("},{"kind":"externalParam","text":"for"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(pl)UIBarPositioning","text":"UIBarPositioning"},{"kind":"text","text":") -> "},{"text":"UIBarPosition","kind":"typeIdentifier","preciseIdentifier":"c:@E@UIBarPosition"}]}},"variantOverrides":[{"patch":[{"path":"\/identifier\/interfaceLanguage","op":"replace","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Instance Method"},{"op":"replace","path":"\/metadata\/title","value":"positionForBar:"},{"op":"replace","path":"\/metadata\/symbolKind","value":"method"},{"op":"replace","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"positionForBar:"}],"path":"\/metadata\/fragments"},{"path":"\/topicSections","value":null,"op":"add"},{"op":"add","path":"\/relationshipsSections","value":null},{"op":"add","value":null,"path":"\/seeAlsoSections"},{"op":"replace","path":"\/primaryContentSections\/0","value":{"declarations":[{"platforms":["iOS"],"languages":["occ"],"tokens":[{"kind":"text","text":"- ("},{"kind":"typeIdentifier","text":"UIBarPosition","preciseIdentifier":"c:@E@UIBarPosition"},{"text":") ","kind":"text"},{"kind":"identifier","text":"positionForBar:"},{"text":"(","kind":"text"},{"text":"id<UIBarPositioning>","kind":"typeIdentifier","preciseIdentifier":"c:Qoobjc(pl)UIBarPositioning"},{"text":") ","kind":"text"},{"kind":"internalParam","text":"bar"},{"text":";","kind":"text"}]}],"kind":"declarations"}},{"value":"ChannelViewController","op":"replace","path":"\/references\/doc:~1~1com.kaleyra.KaleyraVideoSDK~1documentation~1KaleyraVideoSDK~1ChannelViewController\/title"},{"value":[{"text":"ChannelViewController","kind":"identifier"}],"path":"\/references\/doc:~1~1com.kaleyra.KaleyraVideoSDK~1documentation~1KaleyraVideoSDK~1ChannelViewController\/fragments","op":"replace"},{"value":"positionForBar:","op":"replace","path":"\/references\/doc:~1~1com.kaleyra.KaleyraVideoSDK~1documentation~1KaleyraVideoSDK~1ChannelViewController~1position(for:)\/title"},{"path":"\/references\/doc:~1~1com.kaleyra.KaleyraVideoSDK~1documentation~1KaleyraVideoSDK~1ChannelViewController~1position(for:)\/fragments","op":"replace","value":[{"kind":"text","text":"- "},{"text":"positionForBar:","kind":"identifier"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}