{"hierarchy":{"paths":[["doc:\/\/com.kaleyra.KaleyraVideoSDK\/documentation\/KaleyraVideoSDK","doc:\/\/com.kaleyra.KaleyraVideoSDK\/documentation\/KaleyraVideoSDK\/ChannelViewController"]]},"topicSections":[{"title":"Instance Methods","identifiers":["doc:\/\/com.kaleyra.KaleyraVideoSDK\/documentation\/KaleyraVideoSDK\/ChannelViewController\/position(for:)"],"generated":true}],"sections":[],"kind":"article","metadata":{"roleHeading":"API Collection","role":"collectionGroup","modules":[{"name":"KaleyraVideoSDK"}],"title":"UIBarPositioningDelegate Implementations"},"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/kaleyravideosdk\/channelviewcontroller\/uibarpositioningdelegate-implementations"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/kaleyravideosdk\/channelviewcontroller\/uibarpositioningdelegate-implementations"]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"identifier":{"url":"doc:\/\/com.kaleyra.KaleyraVideoSDK\/documentation\/KaleyraVideoSDK\/ChannelViewController\/UIBarPositioningDelegate-Implementations","interfaceLanguage":"swift"},"references":{"doc://com.kaleyra.KaleyraVideoSDK/documentation/KaleyraVideoSDK/ChannelViewController":{"navigatorTitle":[{"kind":"identifier","text":"ChannelViewController"}],"identifier":"doc:\/\/com.kaleyra.KaleyraVideoSDK\/documentation\/KaleyraVideoSDK\/ChannelViewController","url":"\/documentation\/kaleyravideosdk\/channelviewcontroller","abstract":[{"type":"text","text":"A view controller showing the user interface of a chat"}],"role":"symbol","title":"ChannelViewController","type":"topic","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"ChannelViewController"}],"kind":"symbol"},"doc://com.kaleyra.KaleyraVideoSDK/documentation/KaleyraVideoSDK":{"url":"\/documentation\/kaleyravideosdk","role":"collection","kind":"symbol","title":"KaleyraVideoSDK","abstract":[],"identifier":"doc:\/\/com.kaleyra.KaleyraVideoSDK\/documentation\/KaleyraVideoSDK","type":"topic"},"doc://com.kaleyra.KaleyraVideoSDK/documentation/KaleyraVideoSDK/ChannelViewController/position(for:)":{"role":"symbol","navigatorTitle":[{"kind":"identifier","text":"positionForBar:"}],"abstract":[],"kind":"symbol","type":"topic","title":"position(for:)","url":"\/documentation\/kaleyravideosdk\/channelviewcontroller\/position(for:)","identifier":"doc:\/\/com.kaleyra.KaleyraVideoSDK\/documentation\/KaleyraVideoSDK\/ChannelViewController\/position(for:)","fragments":[{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"text":"position","kind":"identifier"},{"kind":"text","text":"("},{"kind":"externalParam","text":"for"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(pl)UIBarPositioning","text":"UIBarPositioning"},{"kind":"text","text":") -> "},{"text":"UIBarPosition","kind":"typeIdentifier","preciseIdentifier":"c:@E@UIBarPosition"}]}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","value":[{"identifiers":["doc:\/\/com.kaleyra.KaleyraVideoSDK\/documentation\/KaleyraVideoSDK\/ChannelViewController\/position(for:)"],"title":"Instance Methods","generated":true}],"path":"\/topicSections"},{"path":"\/seeAlsoSections","op":"add","value":null},{"value":"ChannelViewController","op":"replace","path":"\/references\/doc:~1~1com.kaleyra.KaleyraVideoSDK~1documentation~1KaleyraVideoSDK~1ChannelViewController\/title"},{"op":"replace","path":"\/references\/doc:~1~1com.kaleyra.KaleyraVideoSDK~1documentation~1KaleyraVideoSDK~1ChannelViewController\/fragments","value":[{"text":"ChannelViewController","kind":"identifier"}]},{"value":"positionForBar:","op":"replace","path":"\/references\/doc:~1~1com.kaleyra.KaleyraVideoSDK~1documentation~1KaleyraVideoSDK~1ChannelViewController~1position(for:)\/title"},{"op":"replace","value":[{"text":"- ","kind":"text"},{"kind":"identifier","text":"positionForBar:"}],"path":"\/references\/doc:~1~1com.kaleyra.KaleyraVideoSDK~1documentation~1KaleyraVideoSDK~1ChannelViewController~1position(for:)\/fragments"}],"traits":[{"interfaceLanguage":"occ"}]}]}